MODEL/help/adjflux.h File Reference
adjflux.h File Reference
Functions
integer ntimes real ua real
rlwd real emice real qmet real
t0 parameter (Le=2.25e6, Lei=2.5e6) parameter(stefbol
Variables
integer ntimes real * sw
integer ntimes real tp
integer ntimes real tcutoff
integer ntimes real hice
integer ntimes real hsnow
integer ntimes real ta
integer ntimes real qa
integer ntimes real ua real * psurf
integer ntimes real ua real rhosurf
integer ntimes real ua real delq
integer ntimes real ua real evap
integer ntimes real ua real hsen
integer ntimes real ua real
rlwd real * Le
integer ntimes real ua real
rlwd real Lei
integer ntimes real ua real
rlwd real stefbol
integer ntimes real ua real
rlwd real emice real * x
integer ntimes real ua real
rlwd real emice real tcutc
integer ntimes real ua real
rlwd real emice real a
integer ntimes real ua real
rlwd real emice real b
integer ntimes real ua real
rlwd real emice real tposs
integer ntimes real ua real
rlwd real emice real t
integer ntimes real ua real
rlwd real emice real tlat
integer ntimes real ua real
rlwd real emice real qsen
integer ntimes real ua real
rlwd real emice real qmet real * qlat
integer ntimes real ua real
rlwd real emice real qmet real t4
integer ntimes real ua real
rlwd real emice real qmet real condbar
integer ntimes real ua real
rlwd real emice real qmet real val
integer ntimes real ua real
rlwd real emice real qmet real val2
integer ntimes real ua real
rlwd real emice real qmet real q0
Function Documentation
integer ntimes real ua real rlwd real emice real qmet real t0 parameter (Le = 2.25e6, Lei = 2.5e6)
Referenced by module_snow::calcsnowmelt(), module_snow::rootbrent(), module_snow::snow_density(), module_snow::snowpackenergybalance(), and module_snow::stabilitycorrection().
Variable Documentation
integer ntimes real ua real rlwd real emice real a
Definition at line 3 of file adjflux.h.
Referenced by module_io::rdimgr(), and module_snow::rootbrent().
integer ntimes real ua real rlwd real emice real b
Definition at line 3 of file adjflux.h.
Referenced by module_snow::rootbrent().
integer ntimes real ua real rlwd real emice real qmet real condbar
Definition at line 3 of file adjflux.h.
integer ntimes real ua real delq
Definition at line 3 of file adjflux.h.
integer ntimes real ua real evap
Definition at line 3 of file adjflux.h.
integer ntimes real hice
Definition at line 3 of file adjflux.h.
integer ntimes real ua real hsen
Definition at line 3 of file adjflux.h.
integer ntimes real hsnow
Definition at line 3 of file adjflux.h.
integer ntimes real ua real rlwd real* Le
Definition at line 3 of file adjflux.h.
integer ntimes real ua real rlwd real Lei
Definition at line 3 of file adjflux.h.
integer ntimes real ua real* psurf
Definition at line 3 of file adjflux.h.
integer ntimes real ua real rlwd real emice real qmet real q0
Definition at line 3 of file adjflux.h.
Referenced by module_topmodel::upzbar().
integer ntimes real qa
Definition at line 3 of file adjflux.h.
integer ntimes real ua real rlwd real emice real qmet real* qlat
Definition at line 3 of file adjflux.h.
integer ntimes real ua real rlwd real emice real qsen
Definition at line 3 of file adjflux.h.
integer ntimes real ua real rhosurf
Definition at line 3 of file adjflux.h.
integer ntimes real ua real rlwd real stefbol
Definition at line 3 of file adjflux.h.
integer ntimes real* sw
Definition at line 3 of file adjflux.h.
integer ntimes real ua real rlwd real emice real t
Definition at line 3 of file adjflux.h.
Referenced by catchment_tests_driver(), and module_snow::rootbrent().
integer ntimes real ua real rlwd real emice real qmet real t4
Definition at line 3 of file adjflux.h.
integer ntimes real ta
Definition at line 3 of file adjflux.h.
integer ntimes real ua real rlwd real emice real tcutc
Definition at line 3 of file adjflux.h.
integer ntimes real tcutoff
Definition at line 3 of file adjflux.h.
integer ntimes real ua real rlwd real emice real tlat
Definition at line 3 of file adjflux.h.
integer ntimes real tp
Definition at line 3 of file adjflux.h.
integer ntimes real ua real rlwd real emice real tposs
Definition at line 3 of file adjflux.h.
integer ntimes real ua real rlwd real emice real qmet real val
Definition at line 3 of file adjflux.h.
integer ntimes real ua real rlwd real emice real qmet real val2
Definition at line 3 of file adjflux.h.
integer ntimes real ua real rlwd real emice real* x
Definition at line 3 of file adjflux.h.
Referenced by module_snow::calcsnowmelt(), module_io::factln(), and module_io::write_binary().