MODEL/help/catchlake_s.h File Reference
catchlake_s.h File Reference
Functions
integer icatch (MAX_PIX) real *8 r_lakearea(MAX_CAT)
Variables
integer i
integer ncatch
integer npix
integer pixsiz
Function Documentation
integer icatch (MAX_PIX)
Referenced by module_regional::compute_regional(), module_topmodel::update_catchments(), module_cell::update_cells(), module_regional::update_regional(), and module_topmodel::upzbar().
Variable Documentation
integer i
Definition at line 1 of file catchlake_s.h.
integer ncatch
Definition at line 1 of file catchlake_s.h.
integer npix
Definition at line 1 of file catchlake_s.h.
integer pixsiz
Definition at line 3 of file catchlake_s.h.
Referenced by module_topmodel::catflx(), module_regional::compute_regional(), and module_topmodel::upzbar().