TOPLATS: module_unit_tests Module Reference
module_unit_tests Module Reference
Public Member Functions
subroutine clcf1par_test1 ()
subroutine clcf1par_test2 ()
subroutine clcf3vpd_test1 ()
subroutine clcf3vpd_test2 ()
subroutine clcf4temp_test1 ()
subroutine clcf4temp_test2 ()
subroutine sm_cen_dif_test1 ()
subroutine sm_cen_dif_test2 ()
subroutine soiladapt_test1 ()
subroutine soiladapt_test2 ()
subroutine esat_test1 ()
subroutine esat_test2 ()
subroutine nreb_snow_test1 ()
subroutine nreb_snow_test2 ()
subroutine stabcor_test1 ()
subroutine stabcor_test2 ()
subroutine calcra_test1 ()
subroutine calcra_test2 ()
subroutine calcrain_test1 ()
subroutine calcrain_test2 ()
subroutine calcrsoil_test1 ()
subroutine calcrsoil_test2 ()
subroutine calcrsoil_test3 ()
subroutine calcrsoil_test4 ()
subroutine reset_inf_pars_test1 ()
subroutine reset_inf_pars_test2 ()
subroutine calcsmcond_test1 ()
subroutine calcsmcond_test2 ()
subroutine new_dwnflx_test1 ()
subroutine new_dwnflx_test2 ()
subroutine new_difflx_test1 ()
subroutine new_difflx_test2 ()
subroutine clc_evrz_test1 ()
subroutine clc_evrz_test2 ()
subroutine calcfw_test1 ()
subroutine calcdc_test1 ()
subroutine calcepw_test1 ()
subroutine calcepw_test2 ()
subroutine interstorm_test1 ()
subroutine interstorm_test2 ()
subroutine zero_snowvar_test1 ()
subroutine acttrans_test1 ()
subroutine acttrans_test2 ()
subroutine clcdg_test1 ()
subroutine clcdg_test2 ()
subroutine calc_rs_test1 ()
subroutine calc_rs_test2 ()
subroutine calcrib_test1 ()
subroutine calcrib_test2 ()
subroutine calcwt_test1 ()
subroutine calcwt_test2 ()
subroutine calcnet_test1 ()
subroutine calcnet_test2 ()
subroutine run_unit_tests ()
Detailed Description
Definition at line 1 of file TESTS_DRIVER.f90.
Member Function/Subroutine Documentation
subroutine module_unit_tests::acttrans_test1 ()
Definition at line 893 of file TESTS_DRIVER.f90.
References module_land::acttrans().
Referenced by run_unit_tests().
subroutine module_unit_tests::acttrans_test2 ()
Definition at line 913 of file TESTS_DRIVER.f90.
References module_land::acttrans().
Referenced by run_unit_tests().
subroutine module_unit_tests::calc_rs_test1 ()
Definition at line 973 of file TESTS_DRIVER.f90.
References module_shared::calc_rs().
Referenced by run_unit_tests().
subroutine module_unit_tests::calc_rs_test2 ()
Definition at line 998 of file TESTS_DRIVER.f90.
References module_shared::calc_rs().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcdc_test1 ()
Definition at line 756 of file TESTS_DRIVER.f90.
References module_canopy::calcdc().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcepw_test1 ()
Definition at line 769 of file TESTS_DRIVER.f90.
References module_canopy::calcepw().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcepw_test2 ()
Definition at line 788 of file TESTS_DRIVER.f90.
References module_canopy::calcepw().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcfw_test1 ()
Definition at line 739 of file TESTS_DRIVER.f90.
References module_canopy::calcfw().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcnet_test1 ()
Definition at line 1097 of file TESTS_DRIVER.f90.
References module_canopy::calcnet().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcnet_test2 ()
Definition at line 1129 of file TESTS_DRIVER.f90.
References module_canopy::calcnet().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcra_test1 ()
Definition at line 260 of file TESTS_DRIVER.f90.
References module_shared::calcra().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcra_test2 ()
Definition at line 270 of file TESTS_DRIVER.f90.
References module_shared::calcra().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcrain_test1 ()
Definition at line 280 of file TESTS_DRIVER.f90.
References module_land::calcrain().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcrain_test2 ()
Definition at line 298 of file TESTS_DRIVER.f90.
References module_land::calcrain().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcrib_test1 ()
Definition at line 1023 of file TESTS_DRIVER.f90.
References module_shared::calcrib().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcrib_test2 ()
Definition at line 1040 of file TESTS_DRIVER.f90.
References module_shared::calcrib().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcrsoil_test1 ()
Definition at line 316 of file TESTS_DRIVER.f90.
References module_land::calcrsoil().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcrsoil_test2 ()
Definition at line 339 of file TESTS_DRIVER.f90.
References module_land::calcrsoil().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcrsoil_test3 ()
Definition at line 362 of file TESTS_DRIVER.f90.
References module_land::calcrsoil().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcrsoil_test4 ()
Definition at line 384 of file TESTS_DRIVER.f90.
References module_land::calcrsoil().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcsmcond_test1 ()
Definition at line 485 of file TESTS_DRIVER.f90.
References module_land::calcsmcond().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcsmcond_test2 ()
Definition at line 504 of file TESTS_DRIVER.f90.
References module_land::calcsmcond().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcwt_test1 ()
Definition at line 1057 of file TESTS_DRIVER.f90.
References module_canopy::calcwt().
Referenced by run_unit_tests().
subroutine module_unit_tests::calcwt_test2 ()
Definition at line 1077 of file TESTS_DRIVER.f90.
References module_canopy::calcwt().
Referenced by run_unit_tests().
subroutine module_unit_tests::clc_evrz_test1 ()
Definition at line 675 of file TESTS_DRIVER.f90.
References module_land::clc_evrz().
Referenced by run_unit_tests().
subroutine module_unit_tests::clc_evrz_test2 ()
Definition at line 707 of file TESTS_DRIVER.f90.
References module_land::clc_evrz().
Referenced by run_unit_tests().
subroutine module_unit_tests::clcdg_test1 ()
Definition at line 933 of file TESTS_DRIVER.f90.
References module_land::clcdg().
Referenced by run_unit_tests().
subroutine module_unit_tests::clcdg_test2 ()
Definition at line 953 of file TESTS_DRIVER.f90.
References module_land::clcdg().
Referenced by run_unit_tests().
subroutine module_unit_tests::clcf1par_test1 ()
Definition at line 15 of file TESTS_DRIVER.f90.
References module_atmos::clcf1par().
Referenced by run_unit_tests().
subroutine module_unit_tests::clcf1par_test2 ()
Definition at line 24 of file TESTS_DRIVER.f90.
References module_atmos::clcf1par().
Referenced by run_unit_tests().
subroutine module_unit_tests::clcf3vpd_test1 ()
Definition at line 33 of file TESTS_DRIVER.f90.
References module_atmos::clcf3vpd().
Referenced by run_unit_tests().
subroutine module_unit_tests::clcf3vpd_test2 ()
Definition at line 42 of file TESTS_DRIVER.f90.
References module_atmos::clcf3vpd().
Referenced by run_unit_tests().
subroutine module_unit_tests::clcf4temp_test1 ()
Definition at line 51 of file TESTS_DRIVER.f90.
References module_atmos::clcf4temp().
Referenced by run_unit_tests().
subroutine module_unit_tests::clcf4temp_test2 ()
Definition at line 60 of file TESTS_DRIVER.f90.
References module_atmos::clcf4temp().
Referenced by run_unit_tests().
subroutine module_unit_tests::esat_test1 ()
Definition at line 144 of file TESTS_DRIVER.f90.
References module_atmos::esat().
Referenced by run_unit_tests().
subroutine module_unit_tests::esat_test2 ()
Definition at line 153 of file TESTS_DRIVER.f90.
References module_atmos::esat().
Referenced by run_unit_tests().
subroutine module_unit_tests::interstorm_test1 ()
Definition at line 807 of file TESTS_DRIVER.f90.
References module_canopy::interstorm().
Referenced by run_unit_tests().
subroutine module_unit_tests::interstorm_test2 ()
Definition at line 833 of file TESTS_DRIVER.f90.
References module_canopy::interstorm().
Referenced by run_unit_tests().
subroutine module_unit_tests::new_difflx_test1 ()
Definition at line 605 of file TESTS_DRIVER.f90.
References module_land::new_difflx().
Referenced by run_unit_tests().
subroutine module_unit_tests::new_difflx_test2 ()
Definition at line 640 of file TESTS_DRIVER.f90.
References module_land::new_difflx().
Referenced by run_unit_tests().
subroutine module_unit_tests::new_dwnflx_test1 ()
Definition at line 523 of file TESTS_DRIVER.f90.
References module_land::new_dwnflx().
Referenced by run_unit_tests().
subroutine module_unit_tests::new_dwnflx_test2 ()
Definition at line 564 of file TESTS_DRIVER.f90.
References module_land::new_dwnflx().
Referenced by run_unit_tests().
subroutine module_unit_tests::nreb_snow_test1 ()
Definition at line 162 of file TESTS_DRIVER.f90.
References module_shared::nreb_snow().
Referenced by run_unit_tests().
subroutine module_unit_tests::nreb_snow_test2 ()
Definition at line 188 of file TESTS_DRIVER.f90.
References module_shared::nreb_snow().
Referenced by run_unit_tests().
subroutine module_unit_tests::reset_inf_pars_test1 ()
Definition at line 405 of file TESTS_DRIVER.f90.
References module_land::reset_inf_pars().
Referenced by run_unit_tests().
subroutine module_unit_tests::reset_inf_pars_test2 ()
Definition at line 445 of file TESTS_DRIVER.f90.
References module_land::reset_inf_pars().
Referenced by run_unit_tests().
subroutine module_unit_tests::run_unit_tests ()
Definition at line 1162 of file TESTS_DRIVER.f90.
References acttrans_test1(), acttrans_test2(), calc_rs_test1(), calc_rs_test2(), calcdc_test1(), calcepw_test1(), calcepw_test2(), calcfw_test1(), calcnet_test1(), calcnet_test2(), calcra_test1(), calcra_test2(), calcrain_test1(), calcrain_test2(), calcrib_test1(), calcrib_test2(), calcrsoil_test1(), calcrsoil_test2(), calcrsoil_test3(), calcrsoil_test4(), calcsmcond_test1(), calcsmcond_test2(), calcwt_test1(), calcwt_test2(), clc_evrz_test1(), clc_evrz_test2(), clcdg_test1(), clcdg_test2(), clcf1par_test1(), clcf1par_test2(), clcf3vpd_test1(), clcf3vpd_test2(), clcf4temp_test1(), clcf4temp_test2(), esat_test1(), esat_test2(), fruit::fruit_summary(), fruit::init_fruit(), interstorm_test1(), interstorm_test2(), new_difflx_test1(), new_difflx_test2(), new_dwnflx_test1(), new_dwnflx_test2(), nreb_snow_test1(), nreb_snow_test2(), reset_inf_pars_test1(), reset_inf_pars_test2(), sm_cen_dif_test1(), sm_cen_dif_test2(), soiladapt_test1(), soiladapt_test2(), stabcor_test1(), stabcor_test2(), and zero_snowvar_test1().
Referenced by tests_driver().
subroutine module_unit_tests::sm_cen_dif_test1 ()
Definition at line 69 of file TESTS_DRIVER.f90.
References module_shared::sm_cen_dif().
Referenced by run_unit_tests().
subroutine module_unit_tests::sm_cen_dif_test2 ()
Definition at line 84 of file TESTS_DRIVER.f90.
References module_shared::sm_cen_dif().
Referenced by run_unit_tests().
subroutine module_unit_tests::soiladapt_test1 ()
Definition at line 100 of file TESTS_DRIVER.f90.
References module_shared::soiladapt().
Referenced by run_unit_tests().
subroutine module_unit_tests::soiladapt_test2 ()
Definition at line 122 of file TESTS_DRIVER.f90.
References module_shared::soiladapt().
Referenced by run_unit_tests().
subroutine module_unit_tests::stabcor_test1 ()
Definition at line 214 of file TESTS_DRIVER.f90.
References module_shared::stabcor().
Referenced by run_unit_tests().
subroutine module_unit_tests::stabcor_test2 ()
Definition at line 237 of file TESTS_DRIVER.f90.
References module_shared::stabcor().
Referenced by run_unit_tests().
subroutine module_unit_tests::zero_snowvar_test1 ()
Definition at line 859 of file TESTS_DRIVER.f90.
References module_land::zero_snowvar().
Referenced by run_unit_tests().
The documentation for this module was generated from the following file:
TESTS/TESTS_DRIVER.f90