module_frozen_soil Module Reference
module_frozen_soil Module Reference
Public Member Functions
subroutine ice_change (ipix, rzdthetaidt, tzdthetaidt, f_moss, f_und, tkmidpet, tkmidpet_us, tkmidpet_moss, rzsm1_f, tzsm1_f, bulk_dens, a_ice, b_ice, row, roi, rzsm1_u, rzsm1, tzsm1_u, tzsm1, thetas, thetar, rzdthetaudtemp, dt, rzsm_f, tzsm_f, tsoilold)
subroutine correct (ts, tr, tz1, tzu, tzf, tzof)
subroutine check_in_ice (soilm, val, wrong, ipix)
subroutine check_ice (soilm, nbad, ttt, zsm, tsm, rtdif, ipix, rzdthetaidt, tzdthetaidt, f_moss, f_und, tkmidpet, tkmidpet_us, tkmidpet_moss, rzsm1_f, tzsm1_f, bulk_dens, a_ice, b_ice, row, roi, rzsm1_u, rzsm1, tzsm1_u, tzsm1, thetas, thetar, rzdthetaudtemp, dt, rzsm_f, tzsm_f, tsoilold, wrong)
Detailed Description
Definition at line 1 of file MODULE_FROZEN_SOIL.f90.
Member Function/Subroutine Documentation
subroutine module_frozen_soil::check_ice (real*8 soilm, integer nbad, ttt, zsm, tsm, rtdif, ipix, rzdthetaidt, tzdthetaidt, f_moss, f_und, tkmidpet, tkmidpet_us, tkmidpet_moss, rzsm1_f, tzsm1_f, bulk_dens, a_ice, b_ice, row, roi, rzsm1_u, rzsm1, tzsm1_u, tzsm1, thetas, thetar, rzdthetaudtemp, dt, rzsm_f, tzsm_f, tsoilold, integer wrong)
Definition at line 390 of file MODULE_FROZEN_SOIL.f90.
References a_ice, b_ice, bulk_dens, d0, dt, f_moss, f_und, ipix, roi, row, rzdthetaidt, rzdthetaudtemp, rzsm1, rzsm1_f, rzsm1_u, rzsm_f, soilm, thetar, thetas, tkmidpet, tkmidpet_moss, tkmidpet_us, tsoilold, tzdthetaidt, tzsm1, tzsm1_f, tzsm1_u, and tzsm_f.
Referenced by ice_change().
subroutine module_frozen_soil::check_in_ice (real*8 soilm, integer val, integer wrong, integer ipix)
Definition at line 351 of file MODULE_FROZEN_SOIL.f90.
References d0, and soilm.
Referenced by ice_change().
subroutine module_frozen_soil::correct (real *8 ts, real *8 tr, real *8 tz1, real *8 tzu, real *8 tzf, real *8 tzof)
Definition at line 313 of file MODULE_FROZEN_SOIL.f90.
References d0, and ts.
Referenced by ice_change().
subroutine module_frozen_soil::ice_change (ipix, rzdthetaidt, tzdthetaidt, f_moss, f_und, tkmidpet, tkmidpet_us, tkmidpet_moss, rzsm1_f, tzsm1_f, bulk_dens, a_ice, b_ice, row, roi, rzsm1_u, rzsm1, tzsm1_u, tzsm1, thetas, thetar, rzdthetaudtemp, dt, rzsm_f, tzsm_f, tsoilold)
Definition at line 18 of file MODULE_FROZEN_SOIL.f90.
References a_ice, b_ice, bulk_dens, check_ice(), check_in_ice(), correct(), d0, dt, f_moss, f_und, ipix, roi, row, rtdif, rzdthetaidt, rzdthetaudtemp, rzsm1, rzsm1_f, rzsm1_u, rzsm_f, thetar, thetas, tkmidpet, tkmidpet_moss, tkmidpet_us, tsm, tsoilold, ttt, tzdthetaidt, tzsm1, tzsm1_f, tzsm1_u, tzsm_f, and zsm.
Referenced by module_land::land().
The documentation for this module was generated from the following file:
MODEL/MODULE_FROZEN_SOIL.f90