TOPLATS: module_canopy Module Reference
module_canopy Module Reference
Data Types
type canopy_template
Public Member Functions
subroutine canopy (ipix, GRID_VARS, GRID_VEG, GRID_MET, GLOBAL)
subroutine calcfw (GRID_VARS, GRID_VEG, GRID_CANOPY)
subroutine calcdc (GRID_VARS)
subroutine calcepw (GRID_VARS, GRID_CANOPY, GLOBAL)
subroutine calcwt (GRID_VARS, GRID_VEG, GRID_MET, GLOBAL, GRID_CANOPY)
subroutine interstorm (ipix, GRID_VARS, GLOBAL)
subroutine calcnet (GRID_VARS, GRID_VEG, GLOBAL)
Detailed Description
Definition at line 1 of file MODULE_CANOPY.f90.
Member Function/Subroutine Documentation
subroutine module_canopy::calcdc (type (grid_vars_template) GRID_VARS)
Definition at line 198 of file MODULE_CANOPY.f90.
Referenced by module_unit_tests::calcdc_test1(), and canopy().
subroutine module_canopy::calcepw (type (grid_vars_template) GRID_VARS, type (canopy_template) GRID_CANOPY, type (global_template) GLOBAL)
Definition at line 238 of file MODULE_CANOPY.f90.
Referenced by module_unit_tests::calcepw_test1(), module_unit_tests::calcepw_test2(), and canopy().
subroutine module_canopy::calcfw (type (grid_vars_template) GRID_VARS, type (grid_veg_template) GRID_VEG, type (canopy_template) GRID_CANOPY)
Definition at line 137 of file MODULE_CANOPY.f90.
Referenced by module_unit_tests::calcfw_test1(), and canopy().
subroutine module_canopy::calcnet (type (grid_vars_template) GRID_VARS, type (grid_veg_template) GRID_VEG, type (global_template) GLOBAL)
Definition at line 472 of file MODULE_CANOPY.f90.
Referenced by module_unit_tests::calcnet_test1(), module_unit_tests::calcnet_test2(), and canopy().
subroutine module_canopy::calcwt (type (grid_vars_template) GRID_VARS, type (grid_veg_template) GRID_VEG, type (grid_met_template) GRID_MET, type (global_template) GLOBAL, type (canopy_template) GRID_CANOPY)
Definition at line 287 of file MODULE_CANOPY.f90.
Referenced by module_unit_tests::calcwt_test1(), module_unit_tests::calcwt_test2(), and canopy().
subroutine module_canopy::canopy (integer ipix, type (grid_vars_template) GRID_VARS, type (grid_veg_template) GRID_VEG, type (grid_met_template) GRID_MET, type (global_template) GLOBAL)
Definition at line 28 of file MODULE_CANOPY.f90.
References calcdc(), calcepw(), calcfw(), calcnet(), calcwt(), and interstorm().
Referenced by module_cell::update_cell().
subroutine module_canopy::interstorm (integer ipix, type (grid_vars_template) GRID_VARS, type (global_template) GLOBAL)
Definition at line 358 of file MODULE_CANOPY.f90.
Referenced by canopy(), module_unit_tests::interstorm_test1(), and module_unit_tests::interstorm_test2().
The documentation for this module was generated from the following file:
MODEL/MODULE_CANOPY.f90