module_regional Module Reference
module_regional Module Reference
Public Member Functions
subroutine update_regional (REG, GRID, GLOBAL, CAT)
subroutine instep_regional (REG)
subroutine sumflx_regional (REG, GRID_VARS, GLOBAL, GRID_VEG, GRID_SOIL, GRID_MET, ilandc)
subroutine compute_regional (REG, GLOBAL, GRID, CAT)
subroutine sursat (zw, psic, fw, mul_fac, pr3sat, zrzmax, perrg2, rzsm1, thetas, pr2sat, pr2uns, perrg1, tzsm1, pr1sat, pr1rzs, pr1tzs, pr1uns, satxr, persxr, xinfxr, perixr, ievcon, persac, peruac, perusc, i, ipix)
Detailed Description
Definition at line 1 of file MODULE_REGIONAL.f90.
Member Function/Subroutine Documentation
subroutine module_regional::compute_regional (type (regional_template), intent(inout) REG, type (global_template), intent(in) GLOBAL, type (grid_template), dimension(:), intent(in) GRID, type (catchment_template), dimension(:), intent(in) CAT)
Definition at line 749 of file MODULE_REGIONAL.f90.
References d0, fbsrg, i, icatch(), ipix, isoil(), ivgtyp, ncatch, npix, perixr, perrg1, perrg2, persac, persxr, peruac, pixsiz, pr1rzs, pr1sat, pr1tzs, pr1uns, pr2sat, pr2uns, pr3sat, qbreg, sum, sursat(), and zero.
Referenced by update_regional().
subroutine module_regional::instep_regional (type (regional_template), intent(inout) REG)
Definition at line 64 of file MODULE_REGIONAL.f90.
References zero.
Referenced by update_regional().
subroutine module_regional::sumflx_regional (type (regional_template), intent(inout) REG, type (grid_vars_template), intent(in) GRID_VARS, type (global_template), intent(in) GLOBAL, type (grid_veg_template), intent(in) GRID_VEG, type (grid_soil_template), intent(in) GRID_SOIL, type (grid_met_template), intent(in) GRID_MET, integer ilandc)
Definition at line 203 of file MODULE_REGIONAL.f90.
References bsdew, canclos, d0, dc, dc_us, difrz, diftz, dshact, dspet, dsrz, dstz, dswc, dt, dummy, epwms, epwms_us, etpix(), evtact, evtact_moss, evtact_us, f_moss, f_und, fw, fw_us, gact, gpet, grz, gtz, hact, hpet, i_und, ilandc, inc_frozen, ivgtyp, one, pnet, pptms, rnact, rnpet, runtot, rzrhs, rzsm, rzsm1, rzsm1_u, satxr, swq(), tair, thetas, tkact, tkmid, tkmidpet, tkpet, tskinact_moss, tzrhs, tzsm, tzsm1, tzsm1_u, wcip1, xinfxr, xleact, xleact_moss, xleact_us, xlepet(), xlhv, zero, zrz, and ztz.
Referenced by update_regional().
subroutine module_regional::sursat (real*8 zw, real*8 psic, real*8 fw, real*8 mul_fac, real*8 pr3sat, real*8 zrzmax, real*8 perrg2, real*8 rzsm1, real*8 thetas, real*8 pr2sat, real*8 pr2uns, real*8 perrg1, real*8 tzsm1, real*8 pr1sat, real*8 pr1rzs, real*8 pr1tzs, real*8 pr1uns, real*8 satxr, real*8 persxr, real*8 xinfxr, real*8 perixr, integer ievcon, real*8 persac, real*8 peruac, real*8 perusc, integer i, integer ipix)
Definition at line 1256 of file MODULE_REGIONAL.f90.
References d0, i, ievcon, ipix, one, perixr, perrg1, perrg2, persac, persxr, peruac, pr1rzs, pr1sat, pr1tzs, pr1uns, pr2sat, pr2uns, pr3sat, psic, rzsm1, satxr, thetas, tolsat, tzsm1, xinfxr, zero, zrzmax, and zw.
Referenced by compute_regional().
subroutine module_regional::update_regional (type (regional_template), intent(inout) REG, type (grid_template), dimension(:), intent(in) GRID, type (global_template), intent(in) GLOBAL, type (catchment_template), dimension(:), intent(in) CAT)
Definition at line 19 of file MODULE_REGIONAL.f90.
References compute_regional(), icatch(), ilandc, instep_regional(), ipix, isoil(), and sumflx_regional().
Referenced by toplats_driver().
The documentation for this module was generated from the following file:
MODEL/MODULE_REGIONAL.f90