module_land Module Reference
module_land Module Reference
Public Member Functions
subroutine land (newstorm, ipix, i, dt, inc_frozen, i_2l,
subroutine states (zw0, inc_frozen, i_moss, tkmid_moss, r_mossm_u, r_mossm_f, r_mossm, zw, zbar, ff, atanb, xlamda, psic, zrz, ztz, rzsm1, tzsm1, thetas, zrzmax, iopsmini, thetar, bcbeta, rzsm1_u, tzsm1_u, rzsm1_f, tzsm1_f, tsoilold, bulk_dens, a_ice, b_ice, row, rzsmold, tzsmold, r_mossmold, rzsm, tzsm, r_mossm1, zmoss, r_moss_depth, thetas_moss, rzsm_u, rzsm_f, tzsm_u, tzsm_f, r_mossm1_u, r_mossm1_f, i, a_ice_moss, b_ice_moss, bulk_dens_moss)
subroutine initsm (zw, psic, zrz, ztz, rzsm1, tzsm1, thetas, zrzmax, iopsmini, thetar, bcbeta, rzsm1_u, tzsm1_u, rzsm1_f, tzsm1_f, inc_frozen, tsoilold, bulk_dens, a_ice, b_ice, row)
subroutine infilt (pnet, i_moss, i_und, PackWater_us, SurfWater_us, Swq_us, Outflow_us, dt, PackWater, SurfWater, Swq, Outflow, istmst, cuminf, inc_frozen, rzsmst, rzsm, rzsm_u, thetas, thetar, tolinf, sorp, xk0, psic, bcgamm, bcbeta, deltrz, cc, zw, xinact, satxr, xinfxr, intstm, xinfcp, runtot, irntyp)
subroutine reset_inf_pars (cuminf, zero, rzsmst, rzsm, thetas, tolinf, sorp, two, xk0, psic, thetar, bcgamm, bcbeta, deltrz, cc, one)
subroutine ebsres (inc_frozen, irestype, rsoil, rzsm, srespar1, tkact, srespar2, rzsm_u, srespar3, ravd, iffroz, thetas, tkmid, zmid, zrzmax, smtmp, tzsm, smold, rzsmold, tzsmold, iopthermc, thermc1, thermc2, thetar, heatcapold, psic, bcbeta, quartz, heatcap1, ifcoarse, heatcap2, rocpsoil, row, cph2o, roa, cp, roi, thermc, heatcap, rzdthetaudtemp, dshact, albd, emiss, rahd, ebscap, tcel, vppa, psychr, xlhv, zdeep, Tdeepstep, rsd, rld, toleb, maxnri, dt, i, tkel, zww, za, uzw, zpd, z0m, press, rib, rnetpn, gbspen, epetd, evtact, ievcon, bsdew, z0h, ioppet)
subroutine calcrain (tcel, snow, rain, precip_o, dt)
subroutine transv (epetd, epetd_us, i_und, iopveg, f1par, f3vpd, f4temp, rescan, inc_frozen, ivgtyp, rzsm, rzsm_u, tc, tw, smcond, tzsm, tzsm_u, tc_us, tw_us, smcond_us, f1par_us, f3vpd_us, f4temp_us, rescan_us, vegcap, ravd, vegcap_us, ravd_us, zrz, srzrel, thetas, thetar, psisoi, psic, bcbeta, ikopt, xksrz, xk0, ff, ressoi, rtact, rtdens, psicri, respla, xkrz, ztz, stzrel, xkstz, xktz, Swq, evtact, ievcon, Swq_us, evtact_us, ievcon_us, bsdew, i, ipix)
subroutine maxplevap (zrz, ztz, epetd, inc_frozen, srzrel, rzsm, thetas, thetar, rzsm_u, zero, one, psisoi, psic, bcbeta, ikopt, xksrz, xk0, ff, two, three, ressoi, rtact, rtdens, vegcap, psicri, respla)
subroutine tz_and_rzbal (i, newstorm, inc_frozen, ikopt, ivgtyp, dt,
subroutine new_difflx (ikopt, xksrz, xkstz, ff, zrz, ztz, inc_frozen, rzsm, tzsm, thetas, thetar, bcbeta, psic, difrz, rzsm_u, tzsm_u, diftz)
function diffuse (dz1, dz2, theta1, theta2, thetas, thetar, bcbeta, psic, xksat1, xksat2)
subroutine new_dwnflx (zrz, ikopt, xksrz, xkstz, rzsm, ff, inc_frozen, thetar, thetas, rzsm_u, grz, bcbeta, ztz, gtz, tzsm, tzsm_u)
subroutine clc_evrz (evrz, Swq, Swq_us, ivgtyp, evtact, dc, i_und, i_moss, fw, evtact_us, dc_us, fw_us, evrz_moss, dummy, f_und)
subroutine land_os (rain, snow, thermc2, heatcap, heatcap2, heatcapold, tkactd, tkmidactd, canclos, ievcon, xlhv, row, ivgtyp, xleactd, evtact, bsdew, ioppet, iffroz, tkmid, zmid, zrzmax, smtmp, rzsm, tzsm, smold, rzsmold, tzsmold, iopthermc, thermc1, thetar, thetas, psic, bcbeta, quartz, ifcoarse, heatcap1, rocpsoil, cph2o, roa, cp, roi, thermc, rzdthetaudtemp, iopgveg, iopthermc_v, tcbeta, xlai, tkact, i_2l, f1, f2, f3, emiss, rescan, ravd, rahd, rnactd, hactd, gactd, dshactd, tcel, vppa, psychr, zdeep, Tdeepstep, rsd, r_lup, rld, toleb, maxnri, dt, i, albd, r_sdn, rnetpn, gbspen, rnetd, xled, hd, gd, dshd, tkd, tkmidd, rnact, xleact, hact, gact, dshact, rnetw, xlew, hw, gw, dshw, tkw, tkmidw, dc, fw, tdiff, inc_frozen, ipix, initer, PackWater, SurfWater, Swq, VaporMassFlux, TPack, TSurf, r_MeltEnergy, Outflow, xleact_snow, hact_snow, dens, precip_o, za, zpd, z0h, RaSnow, appa, vpsat, uzw, rn_snow, alb_snow)
subroutine land_us (rain, snow, thermc1, thermc2, heatcap_moss, heatcap, heatcap1, heatcap2, heatcapold, tkactd_us, tkmidactd_us, tskinactd_moss, tkactd_moss, tkmidactd_moss, canclos, ievcon_us, rnact_us, xleact_us, hact_us, gact_us, dshact_us, tkact_us, tkmid_us, rnactd_us, rnetw_us, xleactd_us, xlew_us, hactd_us, hw_us, gactd_us, gw_us, dshactd_us, dshw_us, tkw_us, tkmidw_us, xlai_us, dc_us, fw_us, trlup, ipix, xlhv_ic, row, evtact_us, iffroz_us, tkmid, zmid, zrzmax, smtmp, rzsm, tzsm, smold, rzsmold, tzsmold, iopthermc, thetar, thetas, psic, bcbeta, quartz, ifcoarse, rocpsoil, cph2o, roa, cp, roi, thermc, inc_frozen, rzdthetaudtemp, iopgveg, thermc_us, iopthermc_v, tcbeta_us, xlai, f3, albd_us, emiss_us, ravd_us, rahd_us, rescan_us, tcel_ic, vppa_ic, roa_ic, psychr_ic, zdeep, Tdeepstep, r_sdn, r_ldn, toleb, maxnri, dt, i, rld, rnetd_us, xled_us, hd_us, gd_us, dshd_us, tkd_us, tkmidd_us, initer, ievcon_moss, xleactd_moss, bsdew_moss, evtact_moss, thermc_moss, r_mossm, tskinact_moss, tkact_moss, tkmid_moss, hactd_moss, gactd_moss, dshactd_moss, rav_moss, rah_moss, r_moss_depth, alb_moss, rnactd_moss, emiss_moss, eact_moss, rnet_pot_moss, xle_p_moss, h_p_moss, g_p_moss, tk_p_moss, tkmid_p_moss, tskin_p_moss, zmoss, thetas_moss, rnact_moss, xleact_moss, hact_moss, gact_moss, dshact_moss, gact, Swq_us, precip_u, za, zpd, z0h, RaSnow, alb_snow, appa, vpsat_ic, uzw, PackWater_us, SurfWater_us, VaporMassFlux_us, TPack_us, TSurf_us, r_MeltEnergy_us, Outflow_us, xleact_snow_us, hact_snow_us, rn_snow_us, dens_us, heatcap_us, tkel_ic, eps, ds_p_moss, i_und, i_moss, i_2l)
subroutine engact (canclos, ievcon, xlhv, row, ivgtyp, xleactd, evtact, bsdew, ioppet, iffroz, tkmid, zmid, zrzmax, smtmp, rzsm, tzsm, smold, rzsmold, tzsmold, iopthermc, thermc1, thermc2, thetar, thetas, psic, bcbeta, quartz, ifcoarse, heatcap1, heatcap2, heatcapold, rocpsoil, cph2o, roa, cp, roi, thermc, heatcap, rzdthetaudtemp, iopgveg, iopthermc_v, tcbeta, xlai, tkact, tkactd, tkmidactd, i_2l, f1, f2, f3, emiss, rescan, ravd, rahd, rnactd, hactd, gactd, dshactd, tcel, vppa, psychr, zdeep, Tdeepstep, rsd, r_lup, rld, toleb, maxnri, dt, i, albd, r_sdn, rnetpn, gbspen, rnetd, xled, hd, gd, dshd, tkd, tkmidd, rnact, xleact, hact, gact, dshact, rnetw, xlew, hw, gw, dshw, tkw, tkmidw, dc, fw, tdiff, inc_frozen, ipix, initer)
subroutine calcrsoil (irestype, rsoil, srespar1, srespar2, srespar3, thetas, rzsm, tkact)
subroutine calcsmcond (rzsm, tc, smcond, one, tw, zero)
subroutine calcvegcap (smcond, zero, vegcap, epetd, resist, ravd)
subroutine acttrans (Swq, vegcap, epet, evtact, ievcon, zrz)
subroutine zero_snowvar (PackWater, SurfWater, Swq, VaporMassFlux, TPack, TSurf, r_MeltEnergy, Outflow, xleact_snow, hact_snow, dens)
subroutine clcddif (ddifrzdth1, ddifrzdth2, ddiftzdth2, rzsm, ikopt, xksrz, xkstz, ff, zrz, ztz, bcbeta, thetas, thetar, psic, tzsm)
function clcdg (sm, ikopt, xksrz, ff, zrz, bcbeta, thetas, thetar)
Detailed Description
Definition at line 1 of file MODULE_LAND.f90.
Member Function/Subroutine Documentation
subroutine module_land::acttrans (Swq, vegcap, epet, evtact, ievcon, zrz)
Definition at line 3838 of file MODULE_LAND.f90.
References d0, epet, evtact, ievcon, swq(), vegcap, and zrz.
Referenced by module_unit_tests::acttrans_test1(), module_unit_tests::acttrans_test2(), and transv().
subroutine module_land::calcrain (tcel, snow, rain, precip_o, dt)
Definition at line 1651 of file MODULE_LAND.f90.
References d0, dt, precip_o, rain, snow, and tcel.
Referenced by module_unit_tests::calcrain_test1(), module_unit_tests::calcrain_test2(), land(), land_os(), land_us(), and module_cell::update_cell().
subroutine module_land::calcrsoil (irestype, rsoil, srespar1, srespar2, srespar3, thetas, rzsm, tkact)
Definition at line 3697 of file MODULE_LAND.f90.
References d(), d0, irestype, rsoil, rzsm, srespar1, srespar2, srespar3, thetas, and tkact.
Referenced by module_unit_tests::calcrsoil_test1(), module_unit_tests::calcrsoil_test2(), module_unit_tests::calcrsoil_test3(), module_unit_tests::calcrsoil_test4(), and ebsres().
subroutine module_land::calcsmcond (rzsm, tc, smcond, one, tw, zero)
Definition at line 3762 of file MODULE_LAND.f90.
References d0, one, rzsm, smcond, tc, tw, and zero.
Referenced by module_unit_tests::calcsmcond_test1(), module_unit_tests::calcsmcond_test2(), and transv().
subroutine module_land::calcvegcap (smcond, zero, vegcap, epetd, resist, ravd)
Definition at line 3808 of file MODULE_LAND.f90.
References epetd, ravd, resist, smcond, vegcap, and zero.
Referenced by transv().
subroutine module_land::clc_evrz (evrz, Swq, Swq_us, ivgtyp, evtact, dc, i_und, i_moss, fw, evtact_us, dc_us, fw_us, evrz_moss, dummy, f_und)
Definition at line 3022 of file MODULE_LAND.f90.
References d0, dc, dc_us, dummy, evrz, evrz_moss, evtact, evtact_us, f_und, fw, fw_us, i_moss, i_und, ivgtyp, swq(), and zero.
Referenced by module_unit_tests::clc_evrz_test1(), module_unit_tests::clc_evrz_test2(), and tz_and_rzbal().
subroutine module_land::clcddif (ddifrzdth1, ddifrzdth2, ddiftzdth2, rzsm, ikopt, xksrz, xkstz, ff, zrz, ztz, bcbeta, thetas, thetar, psic, tzsm)
Definition at line 3930 of file MODULE_LAND.f90.
References bcbeta, ddifrzdth1, ddifrzdth2, ddiftzdth2, ff, ikopt, psic, rzsm, thetar, thetas, tzsm, xksrz, xkstz, zrz, and ztz.
Referenced by tz_and_rzbal().
function module_land::clcdg (sm, ikopt, xksrz, ff, zrz, bcbeta, thetas, thetar)
Definition at line 3991 of file MODULE_LAND.f90.
References bcbeta, d0, dgrz, satrel, sm, thetar, thetas, and xksrz.
Referenced by module_unit_tests::clcdg_test1(), module_unit_tests::clcdg_test2(), and tz_and_rzbal().
function module_land::diffuse (dz1, dz2, theta1, theta2, thetas, thetar, bcbeta, psic, xksat1, xksat2)
Definition at line 2822 of file MODULE_LAND.f90.
References bcbeta, d(), d0, df, difflx, dz, dz1, dz2, f1, grad, psic, satrel, theta, theta1, theta2, thetar, thetas, xksat, xksat1, and xksat2.
Referenced by new_difflx().
subroutine module_land::ebsres (inc_frozen, irestype, rsoil, rzsm, srespar1, tkact, srespar2, rzsm_u, srespar3, ravd, iffroz, thetas, tkmid, zmid, zrzmax, smtmp, tzsm, smold, rzsmold, tzsmold, iopthermc, thermc1, thermc2, thetar, heatcapold, psic, bcbeta, quartz, heatcap1, ifcoarse, heatcap2, rocpsoil, row, cph2o, roa, cp, roi, thermc, heatcap, rzdthetaudtemp, dshact, albd, emiss, rahd, ebscap, tcel, vppa, psychr, xlhv, zdeep, Tdeepstep, rsd, rld, toleb, maxnri, dt, i, tkel, zww, za, uzw, zpd, z0m, press, rib, rnetpn, gbspen, epetd, evtact, ievcon, bsdew, z0h, ioppet)
Definition at line 1412 of file MODULE_LAND.f90.
References albd, bcbeta, bsdew, module_shared::calcra(), calcrsoil(), cp, cph2o, d0, dshact, dt, dumds, dumg, dumh, dumrn, dumtk, dumtkmid, dumxle, dvpsdt, ebscap, ebsmf, emiss, epetd, evtact, gbspen, heatcap, heatcap1, heatcap2, heatcapold, i, ievcon, ifcoarse, iffroz, inc_frozen, ioppet, iopthermc, irestype, iter, maxiter, maxnri, module_shared::nreb(), one, press, psic, pstar, psychr, quartz, rahd, ravd, raveff, rib, rld, rnetpn, roa, rocpsoil, roi, row, rsd, rsoil, rzdthetaudtemp, rzsm, rzsm_u, rzsmold, module_shared::sm_cen_dif(), smold, smtmp, module_shared::soiltherm(), srespar1, srespar2, srespar3, module_shared::stabcor(), tacttemp, tcel, thermc, thermc1, thermc2, thetar, thetas, tkact, tkel, tkmid, tmidtemp, toleb, ttemp, two, tzsm, tzsmold, uzw, vpdef, vppa, vpsat, xlhv, z0h, z0m, za, zdeep, zero, zmid, zpd, zrzmax, and zww.
Referenced by land().
subroutine module_land::engact (canclos, ievcon, xlhv, row, ivgtyp, xleactd, evtact, bsdew, ioppet, iffroz, tkmid, zmid, zrzmax, smtmp, rzsm, tzsm, smold, rzsmold, tzsmold, iopthermc, thermc1, thermc2, thetar, thetas, psic, bcbeta, quartz, ifcoarse, heatcap1, heatcap2, heatcapold, rocpsoil, cph2o, roa, cp, roi, thermc, heatcap, rzdthetaudtemp, iopgveg, iopthermc_v, tcbeta, xlai, tkact, tkactd, tkmidactd, i_2l, f1, f2, f3, emiss, rescan, ravd, rahd, rnactd, hactd, gactd, dshactd, tcel, vppa, psychr, zdeep, Tdeepstep, rsd, r_lup, rld, toleb, maxnri, dt, i, albd, r_sdn, rnetpn, gbspen, rnetd, xled, hd, gd, dshd, tkd, tkmidd, rnact, xleact, hact, gact, dshact, rnetw, xlew, hw, gw, dshw, tkw, tkmidw, dc, fw, tdiff, inc_frozen, ipix, initer)
Definition at line 3458 of file MODULE_LAND.f90.
References albd, bcbeta, bsdew, canclos, ccc, cp, cph2o, dc, dshact, dshactd, dshd, dshw, dt, emiss, evtact, f1, f2, f3, fw, gact, gactd, gbspen, gd, gw, hact, hactd, hd, heatcap, heatcap1, heatcap2, heatcapold, hw, i, i_2l, ievcon, ifcoarse, iffroz, inc_frozen, initer, iopgveg, ioppet, iopthermc, iopthermc_v, ipix, ivgtyp, maxnri, module_shared::nreb(), one, psic, psychr, quartz, r_lup, r_sdn, rahd, ravd, rescan, rld, rnact, rnactd, rnetd, rnetpn, rnetw, roa, rocpsoil, roi, row, rsd, rzdthetaudtemp, rzsm, rzsmold, module_shared::sm_cen_dif(), smold, smtmp, module_shared::soiladapt(), module_shared::soiltherm(), tcbeta, tcel, tdiff, tdum1, tdum2, thermc, thermc1, thermc2, thetar, thetas, tkact, tkactd, tkd, tkmid, tkmidactd, tkmidd, tkmidw, tkw, toleb, tzsm, tzsmold, vppa, xlai, xleact, xleactd, xled, xlew, xlhv, zdeep, zero, zmid, and zrzmax.
Referenced by land_os().
subroutine module_land::infilt (pnet, i_moss, i_und, PackWater_us, SurfWater_us, Swq_us, Outflow_us, dt, PackWater, SurfWater, Swq, Outflow, istmst, cuminf, inc_frozen, rzsmst, rzsm, rzsm_u, thetas, thetar, tolinf, sorp, xk0, psic, bcgamm, bcbeta, deltrz, cc, zw, xinact, satxr, xinfxr, intstm, xinfcp, runtot, irntyp)
Definition at line 1179 of file MODULE_LAND.f90.
References bcbeta, bcgamm, cc, cuminf, d0, deltrz, dt, four, i_und, inc_frozen, intstm, irntyp, istmst, one, pnet, precipitation, psic, reset_inf_pars(), runtot, rzsm, rzsm_u, rzsmst, satxr, sorp, swq(), thetar, thetas, tolinf, two, xinact, xinfcp, xinfxr, xk0, zero, and zw.
Referenced by land().
subroutine module_land::initsm (zw, psic, zrz, ztz, rzsm1, tzsm1, thetas, zrzmax, iopsmini, thetar, bcbeta, rzsm1_u, tzsm1_u, rzsm1_f, tzsm1_f, inc_frozen, tsoilold, bulk_dens, a_ice, b_ice, row)
Definition at line 963 of file MODULE_LAND.f90.
References a_ice, b_ice, bcbeta, bulk_dens, d0, inc_frozen, iopsmini, psic, row, rtdif, rzsm1, rzsm1_f, rzsm1_u, thetar, thetas, tsoilold, ttt, tzsm1, tzsm1_f, tzsm1_u, zero, zrz, zrzmax, ztz, and zw.
Referenced by states().
subroutine module_land::land (newstorm, ipix, i, dt, inc_frozen, i_2l)
Definition at line 24 of file MODULE_LAND.f90.
References a_ice, a_ice_moss, alb_moss, alb_snow, albd, albd_us, appa, atanb, b_ice, b_ice_moss, bcbeta, bcgamm, bsdew, bsdew_moss, bulk_dens, bulk_dens_moss, module_shared::calc_rs(), calcrain(), module_snow::calcsnowmelt(), canclos, capflx, cc, corr, cp, cph2o, cuminf, d(), d0, dc, dc_us, deltrz, dens, dens_us, dewrun, difrz, diftz, ds_p_moss, dshact, dshact_moss, dshact_us, dshactd, dshactd_moss, dshactd_us, dshd, dshd_us, dshw, dshw_us, dsrz, dstz, dt, dum, eact_moss, ebscap, ebsres(), emiss, emiss_moss, emiss_us, epet_moss, epetd, epetd_us, eps, evrz_moss, evtact, evtact_moss, evtact_us, extinct, f1, f11, f1par, f1par_us, f2, f3, f3vpd, f3vpd_us, f4temp, f4temp_us, f_moss, f_und, ff, fw, fw_us, fwcat, fwreg, g_p_moss, gact, gact_moss, gact_us, gactd, gactd_moss, gactd_us, gbspen, gd, gd_us, gold, grz, gtz, gw, gw_us, h_p_moss, hact, hact_moss, hact_snow, hact_snow_us, hact_us, hactd, hactd_moss, hactd_us, hd, hd_us, heatcap, heatcap1, heatcap2, heatcap_moss, heatcap_us, heatcapold, hw, hw_us, i, i_2l, i_moss, i_und, module_frozen_soil::ice_change(), idifind, ievcon, ievcon_moss, ievcon_us, ifcoarse, iffroz, iffroz_us, ikopt, inc_frozen, infilt(), initer, intstm, intstm_moss, intstp, iopgveg, ioppet, iopsmini, iopthermc, iopthermc_v, iopveg, ipix, irestype, irntyp, istmst, istmst_moss, istorm, ivgtyp, land_os(), land_us(), maxnri, newstorm, module_shared::nreb_snow(), p1, p2, p3, par, perixr, perrg1, perrg2, persac, persxr, peruac, pnet, pptms, pr1rzs, pr1sat, pr1tzs, pr1uns, pr2sat, pr2uns, pr3sat, precip_o, precip_u, press, psic, psicri, psisoi, psychr, psychr_ic, quartz, r_ldn, r_lup, r_moss_depth, r_mossm, r_mossm1, r_mossm1_f, r_mossm1_u, r_mossm_f, r_mossm_u, r_mossmold, r_sdn, rah_moss, rahd, rahd_us, rain, rasnow, rav_moss, ravd, ravd_us, rescan, rescan_us, respla, ressoi, rib, rib_moss, rld, rn_snow, rn_snow_us, rnact, rnact_moss, rnact_us, rnactd, rnactd_moss, rnactd_us, rnet_pot_moss, rnetd, rnetd_us, rnetpn, rnetw, rnetw_us, roa, roa_ic, rocpsoil, roi, row, rs_over, rs_under, rsd, rsoil, rtact, rtdens, runtot, rzdthetaidt, rzdthetaudtemp, rzrhs, rzsm, rzsm1, rzsm1_f, rzsm1_u, rzsm_f, rzsm_test, rzsm_u, rzsm_u_test, rzsmold, rzsmst, satxr, sesq, module_shared::sm_cen_dif(), smcond, smcond_us, smold, smtmp, snow, module_shared::soiladapt(), module_shared::soiltherm(), sorp, srespar1, srespar1_moss, srespar2, srespar2_moss, srespar3, srespar3_moss, srzrel, states(), stzrel, swq(), tc, tc_us, tcbeta, tcbeta_us, tcel, tcel_ic, tdiff, thermc, thermc1, thermc2, thermc_moss, thermc_us, thetar, thetas, thetas_moss, tk_p_moss, tkact, tkact_moss, tkact_us, tkactd, tkactd_moss, tkactd_us, tkd, tkd_us, tkel, tkel_ic, tkmid, tkmid_moss, tkmid_p_moss, tkmid_us, tkmidactd, tkmidactd_moss, tkmidactd_us, tkmidd, tkmidd_us, tkmidpet, tkmidpet_moss, tkmidpet_us, tkmidw, tkmidw_us, tkw, tkw_us, toleb, tolinf, transv(), trlup, tskin_p_moss, tskinact_moss, tskinactd_moss, tsnow, tsoilold, tsurf, tw, tw_us, tz_and_rzbal(), tzdthetaidt, tzrhs, tzsm, tzsm1, tzsm1_f, tzsm1_u, tzsm_f, tzsm_test, tzsm_u, tzsm_u_test, tzsmold, uzw, vegcap, vegcap_us, vppa, vppa_ic, vpsat, vpsat_ic, wcip1, xinact, xinfcp, xinfxr, xk0, xkrz, xksrz, xkstz, xktz, xlai, xlai_us, xlamda, xle_act_moss, xle_p_moss, xleact, xleact_moss, xleact_snow, xleact_snow_us, xleact_us, xleactd, xleactd_moss, xleactd_us, xled, xled_us, xlew, xlew_us, xlhv, xlhv_ic, z0h, z0h_moss, z0m, z0m_moss, za, zbar, zdeep, zero, zmid, zmoss, zpd, zpd_moss, zpd_us, zrz, zrzmax, ztz, zw, zw0, and zww.
Referenced by module_cell::update_cell().
subroutine module_land::land_os (rain, snow, thermc2, heatcap, heatcap2, heatcapold, tkactd, tkmidactd, canclos, ievcon, xlhv, row, ivgtyp, xleactd, evtact, bsdew, ioppet, iffroz, tkmid, zmid, zrzmax, smtmp, rzsm, tzsm, smold, rzsmold, tzsmold, iopthermc, thermc1, thetar, thetas, psic, bcbeta, quartz, ifcoarse, heatcap1, rocpsoil, cph2o, roa, cp, roi, thermc, rzdthetaudtemp, iopgveg, iopthermc_v, tcbeta, xlai, tkact, i_2l, f1, f2, f3, emiss, rescan, ravd, rahd, rnactd, hactd, gactd, dshactd, tcel, vppa, psychr, zdeep, Tdeepstep, rsd, r_lup, rld, toleb, maxnri, dt, i, albd, r_sdn, rnetpn, gbspen, rnetd, xled, hd, gd, dshd, tkd, tkmidd, rnact, xleact, hact, gact, dshact, rnetw, xlew, hw, gw, dshw, tkw, tkmidw, dc, fw, tdiff, inc_frozen, ipix, initer, PackWater, SurfWater, Swq, VaporMassFlux, TPack, TSurf, r_MeltEnergy, Outflow, xleact_snow, hact_snow, dens, precip_o, za, zpd, z0h, RaSnow, appa, vpsat, uzw, rn_snow, alb_snow)
Definition at line 3194 of file MODULE_LAND.f90.
References alb_snow, albd, appa, bcbeta, bsdew, calcrain(), module_snow::calcsnowmelt(), canclos, cp, cph2o, d0, dc, dens, dshact, dshactd, dshd, dshw, dt, emiss, engact(), evtact, f1, f2, f3, fw, gact, gactd, gbspen, gd, gw, hact, hact_snow, hactd, hd, heatcap, heatcap1, heatcap2, heatcapold, hw, i, i_2l, ievcon, ifcoarse, iffroz, inc_frozen, initer, iopgveg, ioppet, iopthermc, iopthermc_v, ipix, ivgtyp, maxnri, module_shared::nreb_snow(), precip_o, psic, psychr, quartz, r_lup, r_sdn, rahd, rain, rasnow, ravd, rescan, rld, rn_snow, rnact, rnactd, rnetd, rnetpn, rnetw, roa, rocpsoil, roi, row, rsd, rzdthetaudtemp, rzsm, rzsmold, smold, smtmp, snow, swq(), tcbeta, tcel, tdiff, thermc, thermc1, thermc2, thetar, thetas, tkact, tkactd, tkd, tkmid, tkmidactd, tkmidd, tkmidw, tkw, toleb, tsnow, tsurf, tzsm, tzsmold, uzw, vppa, vpsat, xlai, xleact, xleact_snow, xleactd, xled, xlew, xlhv, z0h, za, zdeep, zero_snowvar(), zmid, zpd, and zrzmax.
Referenced by land().
subroutine module_land::land_us (real*8 rain, real*8 snow, real*8 thermc1, real*8 thermc2, real*8 heatcap_moss, real*8 heatcap, real*8 heatcap1, real*8 heatcap2, real*8 heatcapold, real*8 tkactd_us, real*8 tkmidactd_us, real*8 tskinactd_moss, real*8 tkactd_moss, real*8 tkmidactd_moss, real*8 canclos, integer ievcon_us, real*8 rnact_us, real*8 xleact_us, real*8 hact_us, real*8 gact_us, real*8 dshact_us, real*8 tkact_us, real*8 tkmid_us, real*8 rnactd_us, real*8 rnetw_us, real*8 xleactd_us, real*8 xlew_us, real*8 hactd_us, real*8 hw_us, real*8 gactd_us, real*8 gw_us, real*8 dshactd_us, real*8 dshw_us, real*8 tkw_us, real*8 tkmidw_us, real*8 xlai_us, real*8 dc_us, real*8 fw_us, real*8 trlup, integer ipix, real*8 xlhv_ic, real*8 row, real*8 evtact_us, integer iffroz_us, real*8 tkmid, real*8 zmid, real*8 zrzmax, real*8 smtmp, real*8 rzsm, real*8 tzsm, real*8 smold, real*8 rzsmold, real*8 tzsmold, integer iopthermc, real*8 thetar, real*8 thetas, real*8 psic, real*8 bcbeta, real*8 quartz, integer ifcoarse, real*8 rocpsoil, real*8 cph2o, real*8 roa, real*8 cp, real*8 roi, real*8 thermc, integer inc_frozen, real*8 rzdthetaudtemp, integer iopgveg, real*8 thermc_us, integer iopthermc_v, real*8 tcbeta_us, real*8 xlai, real*8 f3, real*8 albd_us, real*8 emiss_us, real*8 ravd_us, real*8 rahd_us, real*8 rescan_us, real*8 tcel_ic, real*8 vppa_ic, real*8 roa_ic, real*8 psychr_ic, real*8 zdeep, real*8 Tdeepstep, real*8 r_sdn, real*8 r_ldn, real*8 toleb, integer maxnri, real*8 dt, integer i, real*8 rld, real*8 rnetd_us, real*8 xled_us, real*8 hd_us, real*8 gd_us, real*8 dshd_us, real*8 tkd_us, real*8 tkmidd_us, integer initer, integer ievcon_moss, real*8 xleactd_moss, real*8 bsdew_moss, real*8 evtact_moss, real*8 thermc_moss, real*8 r_mossm, real*8 tskinact_moss, real*8 tkact_moss, real*8 tkmid_moss, real*8 hactd_moss, real*8 gactd_moss, real*8 dshactd_moss, real*8 rav_moss, real*8 rah_moss, real*8 r_moss_depth, real*8 alb_moss, real*8 rnactd_moss, real*8 emiss_moss, real*8 eact_moss, real*8 rnet_pot_moss, real*8 xle_p_moss, real*8 h_p_moss, real*8 g_p_moss, real*8 tk_p_moss, real*8 tkmid_p_moss, real*8 tskin_p_moss, real*8 zmoss, real*8 thetas_moss, real*8 rnact_moss, real*8 xleact_moss, real*8 hact_moss, real*8 gact_moss, real*8 dshact_moss, real*8 gact, real*8 Swq_us, real*8 precip_u, real*8 za, real*8 zpd, real*8 z0h, real*8 RaSnow, real*8 alb_snow, real*8 appa, real*8 vpsat_ic, real*8 uzw, real*8 PackWater_us, real*8 SurfWater_us, real*8 VaporMassFlux_us, real*8 TPack_us, real*8 TSurf_us, real*8 r_MeltEnergy_us, real*8 Outflow_us, real*8 xleact_snow_us, real*8 hact_snow_us, real*8 rn_snow_us, real*8 dens_us, real*8 heatcap_us, real*8 tkel_ic, real*8 eps, real*8 ds_p_moss, integer i_und, integer i_moss, integer i_2l)
Definition at line 3326 of file MODULE_LAND.f90.
References alb_moss, alb_snow, albd_us, appa, bcbeta, bsdew_moss, calcrain(), module_snow::calcsnowmelt(), canclos, cp, cph2o, d0, dc_us, dens_us, ds_p_moss, dshact_moss, dshact_us, dshactd_moss, dshactd_us, dshd_us, dshw_us, dt, eact_moss, emiss_moss, emiss_us, eps, evtact_moss, evtact_us, f3, five, four, fw_us, g_p_moss, gact, gact_moss, gact_us, gactd_moss, gactd_us, gd_us, gw_us, h_p_moss, hact_moss, hact_snow_us, hact_us, hactd_moss, hactd_us, hd_us, heatcap1, heatcap2, heatcap_us, heatcapold, hw_us, i, i_2l, i_moss, i_und, ievcon_moss, ievcon_us, ifcoarse, iffroz_us, inc_frozen, initer, iopgveg, iopthermc, iopthermc_v, ipix, maxnri, one, precip_u, psic, psychr_ic, quartz, r_ldn, r_moss_depth, r_mossm, r_sdn, rah_moss, rahd_us, rain, rasnow, rav_moss, ravd_us, rescan_us, rld, rn_snow_us, rnact_moss, rnact_us, rnactd_moss, rnactd_us, rnet_pot_moss, rnetd_us, rnetw_us, roa, roa_ic, rocpsoil, roi, row, rzdthetaudtemp, rzsm, rzsmold, six, smold, smtmp, snow, tcbeta_us, tcel_ic, thermc, thermc_moss, thermc_us, thetar, thetas, thetas_moss, three, tk_p_moss, tkact_moss, tkact_us, tkactd_moss, tkactd_us, tkd_us, tkel_ic, tkmid, tkmid_moss, tkmid_p_moss, tkmid_us, tkmidactd_moss, tkmidactd_us, tkmidd_us, tkmidw_us, tkw_us, toleb, trlup, tskin_p_moss, tskinact_moss, tskinactd_moss, tsnow, two, tzsm, tzsmold, uzw, vppa_ic, vpsat_ic, xlai, xlai_us, xle_p_moss, xleact_moss, xleact_snow_us, xleact_us, xleactd_moss, xleactd_us, xled_us, xlew_us, xlhv_ic, z0h, za, zdeep, zero, zero_snowvar(), zmid, zmoss, zpd, and zrzmax.
Referenced by land().
subroutine module_land::maxplevap (zrz, ztz, epetd, inc_frozen, srzrel, rzsm, thetas, thetar, rzsm_u, zero, one, psisoi, psic, bcbeta, ikopt, xksrz, xk0, ff, two, three, ressoi, rtact, rtdens, vegcap, psicri, respla)
Definition at line 1931 of file MODULE_LAND.f90.
References bcbeta, epetd, ff, ikopt, inc_frozen, one, psic, psicri, psisoi, respla, ressoi, rtact, rtdens, rzsm, rzsm_u, srzrel, thetar, thetas, three, two, vegcap, xk0, xkrz, xksrz, zero, zrz, and ztz.
Referenced by transv().
subroutine module_land::new_difflx (ikopt, xksrz, xkstz, ff, zrz, ztz, inc_frozen, rzsm, tzsm, thetas, thetar, bcbeta, psic, difrz, rzsm_u, tzsm_u, diftz)
Definition at line 2679 of file MODULE_LAND.f90.
References bcbeta, d0, diffuse(), difrz, diftz, inc_frozen, psic, rzsm, rzsm_u, thetar, thetas, tolsat, tzsm, tzsm_u, xksrz, xkstz, zero, zrz, and ztz.
Referenced by module_unit_tests::new_difflx_test1(), module_unit_tests::new_difflx_test2(), and tz_and_rzbal().
subroutine module_land::new_dwnflx (zrz, ikopt, xksrz, xkstz, rzsm, ff, inc_frozen, thetar, thetas, rzsm_u, grz, bcbeta, ztz, gtz, tzsm, tzsm_u)
Definition at line 2890 of file MODULE_LAND.f90.
References bcbeta, grz, gtz, inc_frozen, one, relsrz, rzsm, rzsm_u, thetar, thetas, three, two, tzsm, tzsm_u, xksrz, xkstz, zero, zrz, and ztz.
Referenced by module_unit_tests::new_dwnflx_test1(), module_unit_tests::new_dwnflx_test2(), and tz_and_rzbal().
subroutine module_land::reset_inf_pars (cuminf, zero, rzsmst, rzsm, thetas, tolinf, sorp, two, xk0, psic, thetar, bcgamm, bcbeta, deltrz, cc, one)
Definition at line 1363 of file MODULE_LAND.f90.
References bcbeta, bcgamm, cc, cuminf, d0, deltrz, one, psic, rzsm, rzsmst, sorp, thetar, thetas, tolinf, two, xk0, and zero.
Referenced by infilt(), module_unit_tests::reset_inf_pars_test1(), and module_unit_tests::reset_inf_pars_test2().
subroutine module_land::states (zw0, inc_frozen, i_moss, tkmid_moss, r_mossm_u, r_mossm_f, r_mossm, zw, zbar, ff, atanb, xlamda, psic, zrz, ztz, rzsm1, tzsm1, thetas, zrzmax, iopsmini, thetar, bcbeta, rzsm1_u, tzsm1_u, rzsm1_f, tzsm1_f, tsoilold, bulk_dens, a_ice, b_ice, row, rzsmold, tzsmold, r_mossmold, rzsm, tzsm, r_mossm1, zmoss, r_moss_depth, thetas_moss, rzsm_u, rzsm_f, tzsm_u, tzsm_f, r_mossm1_u, r_mossm1_f, i, a_ice_moss, b_ice_moss, bulk_dens_moss)
Definition at line 760 of file MODULE_LAND.f90.
References a_ice, a_ice_moss, atanb, b_ice, b_ice_moss, bcbeta, bulk_dens, bulk_dens_moss, d0, ff, i, inc_frozen, initsm(), iopsmini, one, psic, r_moss_depth, r_mossm, r_mossm1, r_mossm1_f, r_mossm1_u, r_mossm_f, r_mossm_u, r_mossmold, row, rzsm, rzsm1, rzsm1_f, rzsm1_u, rzsm_f, rzsm_u, rzsmold, thetar, thetas, thetas_moss, tsoilold, tzsm, tzsm1, tzsm1_f, tzsm1_u, tzsm_f, tzsm_u, tzsmold, xlamda, zbar, zero, zmoss, zrz, zrzmax, ztz, zw, and zw0.
Referenced by land().
subroutine module_land::transv (epetd, epetd_us, i_und, iopveg, f1par, f3vpd, f4temp, rescan, inc_frozen, ivgtyp, rzsm, rzsm_u, tc, tw, smcond, tzsm, tzsm_u, tc_us, tw_us, smcond_us, f1par_us, f3vpd_us, f4temp_us, rescan_us, vegcap, ravd, vegcap_us, ravd_us, zrz, srzrel, thetas, thetar, psisoi, psic, bcbeta, ikopt, xksrz, xk0, ff, ressoi, rtact, rtdens, psicri, respla, xkrz, ztz, stzrel, xkstz, xktz, Swq, evtact, ievcon, Swq_us, evtact_us, ievcon_us, bsdew, integer i, integer ipix)
Definition at line 1687 of file MODULE_LAND.f90.
References acttrans(), bcbeta, bsdew, calcsmcond(), calcvegcap(), d0, epetd, epetd_us, evtact, evtact_us, f1par, f1par_us, f3vpd, f3vpd_us, f4temp, f4temp_us, ff, i, i_und, ievcon, ievcon_us, ikopt, inc_frozen, iopveg, ipix, ivgtyp, maxplevap(), one, psic, psicri, psisoi, ravd, ravd_us, rescan, rescan_us, resist, respla, ressoi, rtact, rtdens, rzsm, rzsm_u, smcond, smcond_us, srzrel, stzrel, swq(), tc, tc_us, thetar, thetas, three, tw, tw_us, two, tzsm, tzsm_u, vegcap, vegcap_us, xk0, xkrz, xksrz, xkstz, xktz, zero, zrz, and ztz.
Referenced by land().
subroutine module_land::tz_and_rzbal (i, newstorm, inc_frozen, ikopt, ivgtyp, dt)
Definition at line 2050 of file MODULE_LAND.f90.
References bcbeta, bsdew, case_flag, clc_evrz(), clcddif(), clcdg(), cor_flx_rz, cor_flx_tz, cuminf, d0, d2rzsmdt2, dc, dc_us, ddifrzdth1, ddifrzdth2, ddiftzdth2, del_rzsm, dewrun, dewrz, dgrzdth1, dgrzdth2, dgtzdth1, dgtzdth2, difrz, difrz_sum, diftz, dsrz, dstz, dt, dtsrzflx, dtstzflx, dummy, evrz_moss, evtact, evtact_us, evtran_rz, evtran_tz, explicit_weight, f11, f_und, ff, fw, fw_us, grz, grz_sum, gtz, gtz_sum, i, i_moss, i_und, ikopt, implicit_weight, inc_frozen, iter, ivgtyp, max_iter, new_difflx(), new_dwnflx(), newstorm, one, psic, runtot, rzrhs, rzsm, rzsm0, rzsm1, rzsm1old, rzsm_u, satxr, srzflx, stzflx, swq(), thetar, thetas, two, tzrhs, tzsm, tzsm0, tzsm1, tzsm1new, tzsm1old, tzsm_u, xinact, xk0, xksrz, xkstz, zero, zrz, zrzmax, ztz, and zw0.
Referenced by land().
subroutine module_land::zero_snowvar (PackWater, SurfWater, Swq, VaporMassFlux, TPack, TSurf, r_MeltEnergy, Outflow, xleact_snow, hact_snow, dens)
Definition at line 3897 of file MODULE_LAND.f90.
References d0, dens, hact_snow, swq(), tsurf, and xleact_snow.
Referenced by land_os(), land_us(), and module_unit_tests::zero_snowvar_test1().
The documentation for this module was generated from the following file:
MODEL/MODULE_LAND.f90