fruit_util Module Reference
fruit_util Module Reference
Data Types
interface equals
interface strip
interface to_s
Private Member Functions
character(len=500) function to_s_int_ (value)
character(len=500) function to_s_real_ (value)
character(len=500) function to_s_double_ (value)
character(len=500) function to_s_complex_ (value)
character(len=500) function to_s_double_complex_ (value)
character(len=500) function to_s_logical_ (value)
character(len=500) function to_s_string_ (value)
character(len=500) function strip_ (value)
character(len=length) function strip_length_ (value, length)
logical function equalepsilon (number1, number2, epsilon)
logical function floatequal (number1, number2)
logical function doubleprecisionequal (number1, number2)
logical function integerequal (number1, number2)
logical function stringequal (str1, str2)
logical function logicalequal (l1, l2)
Detailed Description
Definition at line 1 of file fruit_util.f90.
Member Function/Subroutine Documentation
logical function fruit_util::doubleprecisionequal (double precision, intent(in) number1, double precision, intent(in) number2) private
Definition at line 157 of file fruit_util.f90.
logical function fruit_util::equalepsilon (real, intent(in) number1, real, intent(in) number2, real, intent(in) epsilon) private
Definition at line 118 of file fruit_util.f90.
logical function fruit_util::floatequal (real, intent(in) number1, real, intent(in) number2) private
Definition at line 137 of file fruit_util.f90.
logical function fruit_util::integerequal (integer, intent(in) number1, integer, intent(in) number2) private
Definition at line 178 of file fruit_util.f90.
logical function fruit_util::logicalequal (logical, intent(in) l1, logical, intent(in) l2) private
Definition at line 202 of file fruit_util.f90.
logical function fruit_util::stringequal (character(*), intent(in) str1, character(*), intent(in) str2) private
Definition at line 191 of file fruit_util.f90.
character(len=500) function fruit_util::strip_ (character(len=*), intent(in) value) private
Definition at line 92 of file fruit_util.f90.
References fruit_util::strip::strip_().
character(len= length) function fruit_util::strip_length_ (character(len=*), intent(in) value, integer, intent(in) length) private
Definition at line 99 of file fruit_util.f90.
References fruit_util::strip::strip_length_().
character(len=500) function fruit_util::to_s_complex_ (complex, intent(in) value) private
Definition at line 58 of file fruit_util.f90.
References fruit_util::to_s::to_s_complex_().
character(len=500) function fruit_util::to_s_double_ (double precision, intent(in) value) private
Definition at line 49 of file fruit_util.f90.
References fruit_util::to_s::to_s_double_().
character(len=500) function fruit_util::to_s_double_complex_ (complex(kind=kind(1.0d0)), intent(in) value) private
Definition at line 67 of file fruit_util.f90.
References fruit_util::to_s::to_s_double_complex_().
character(len=500) function fruit_util::to_s_int_ (integer, intent(in) value) private
Definition at line 31 of file fruit_util.f90.
References fruit_util::to_s::to_s_int_().
character(len=500) function fruit_util::to_s_logical_ (logical, intent(in) value) private
Definition at line 76 of file fruit_util.f90.
References fruit_util::to_s::to_s_logical_().
character(len=500) function fruit_util::to_s_real_ (real, intent(in) value) private
Definition at line 40 of file fruit_util.f90.
References fruit_util::to_s::to_s_real_().
character(len=500) function fruit_util::to_s_string_ (character(len=*), intent(in) value) private
Definition at line 85 of file fruit_util.f90.
References fruit_util::to_s::to_s_string_().
The documentation for this module was generated from the following file:
TESTS/fruit/fruit_util.f90