TOPLATS: module_io Module Reference
module_io Module Reference
Data Types
interface extract_info_general_file
type io_template
Public Member Functions
subroutine initialize_model (GLOBAL, GRID, REG, CAT, IO)
Subroutine to read in model parameters and initialize the variables.
subroutine read_data (GLOBAL, GRID, CAT, IO, i)
Subroutine to read in the model parameters.
subroutine write_data (GLOBAL, GRID, IO, REG, i)
Subroutine to output data to file.
subroutine finalize_model (GLOBAL)
Finalize model and close files.
subroutine rdatmo (i, MET, GLOBAL, IO)
Subroutine to read in and pass meteorological data (e.g. rainfall).
subroutine rdforc (pixdat, nrow, ncol, ipixnum, data_in)
Subroutine to convert data to original setup.
subroutine rddata (GLOBAL, GRID, REG, CAT, IO)
Subroutine to open input/output files, read and initialize time in-variant data.
subroutine rdveg_update (GLOBAL, GRID)
Subroutine to update the vegetation parameters.
subroutine rdtpmd (GRID, CAT, IO, GLOBAL)
Subroutine to read in and initialize topmodel parameters and the soils-topographic index map.
subroutine file_open (GLOBAL)
Subroutine to handle opening and closing the input files.
subroutine file_close (GLOBAL)
Subroutine to close all open files.
subroutine write_regional (i, REG, GLOBAL)
subroutine to write regional variables to file
subroutine rdveg (GLOBAL, CAT, GRID, REG, IO)
Subroutine to read and initiailize simulation constant vegetation and land cover parameters.
subroutine inisim (GLOBAL, IO, GRID)
Subroutine to initialize simulation total water balance variables.
subroutine write_binary (datain, rmult, nrow, ncol, ipixnum, i, GLOBAL)
Subroutine to write raw binary data to the output file.
subroutine rdsoil (GLOBAL, CAT, GRID, IO)
Subroutine to read and initialize time in-variant soil parameters.
subroutine rdimgi (ia, iu, nrow, ncol, ipixnum)
Subroutine to read in an image of integers and return an array of these values indexed by the soils-topographi! index pixel numbers.
subroutine rdimgr (a, iu, nrow, ncol, ipixnum)
Subroutine to read in an image of 4 byte reals and return an array of these values indexed by the soils-topographic index pixel numbers.
subroutine rdatb (atb, nrow, ncol, ipixnum, ixpix, iypix, npix, fp)
Subroutine to read in the topographi! index image and set up at translation between the pixel number and the image row.and.& column.
real *8 function factln (i)
Returns the natural log of the i factorial.
subroutine read_general_file (GLOBAL)
Subroutine to read the general parameters file.
subroutine extract_info_general_file_int (strid, GLOBAL, read_arg)
Subroutine to extract all integer variables from the general parameters file.
subroutine extract_info_general_file_string (strid, GLOBAL, read_arg)
Subroutine to extract all string variables from the general parameters file.
subroutine extract_info_general_file_double (strid, GLOBAL, read_arg)
Subroutine to extract all double precision variables from the general parameters file.
Detailed Description
Definition at line 1 of file MODULE_IO.f90.
Member Function/Subroutine Documentation
subroutine module_io::extract_info_general_file_double (character(len=*) strid, type (global_template), intent(inout) GLOBAL, real*8 read_arg)
Subroutine to extract all double precision variables from the general parameters file.
Definition at line 1784 of file MODULE_IO.f90.
subroutine module_io::extract_info_general_file_int (character(*) strid, type (global_template), intent(inout) GLOBAL, integer read_arg)
Subroutine to extract all integer variables from the general parameters file.
Definition at line 1725 of file MODULE_IO.f90.
subroutine module_io::extract_info_general_file_string (character(len=*) strid, type (global_template), intent(inout) GLOBAL, character(len=400) read_arg)
Subroutine to extract all string variables from the general parameters file.
Definition at line 1754 of file MODULE_IO.f90.
real*8 function module_io::factln (integer i)
Returns the natural log of the i factorial.
Definition at line 1606 of file MODULE_IO.f90.
Referenced by rdsoil().
subroutine module_io::file_close (type(global_template), intent(in) GLOBAL)
Subroutine to close all open files.
Definition at line 672 of file MODULE_IO.f90.
Referenced by finalize_model().
subroutine module_io::file_open (type (global_template), intent(inout) GLOBAL)
Subroutine to handle opening and closing the input files.
Definition at line 606 of file MODULE_IO.f90.
Referenced by initialize_model().
subroutine module_io::finalize_model (type (global_template), intent(inout) GLOBAL)
Finalize model and close files.
Definition at line 151 of file MODULE_IO.f90.
References file_close().
Referenced by toplats_driver().
subroutine module_io::inisim (type (global_template), intent(inout) GLOBAL, type (io_template), intent(inout) IO, type (grid_template), dimension(:), intent(inout), allocatable GRID)
Subroutine to initialize simulation total water balance variables.
Definition at line 982 of file MODULE_IO.f90.
Referenced by rddata().
subroutine module_io::initialize_model (type (global_template), intent(inout) GLOBAL, type (grid_template), dimension(:), intent(inout), allocatable GRID, type (regional_template), intent(inout) REG, type (catchment_template), dimension(:), intent(inout), allocatable CAT, type (io_template), intent(inout) IO)
Subroutine to read in model parameters and initialize the variables.
Definition at line 27 of file MODULE_IO.f90.
References file_open(), rddata(), and read_general_file().
Referenced by toplats_driver().
subroutine module_io::rdatb (real*8, dimension(nrow*ncol) atb, integer nrow, integer ncol, integer, dimension(nrow,ncol) ipixnum, integer, dimension(nrow*ncol) ixpix, integer, dimension(nrow*ncol) iypix, integer npix, integer fp)
Subroutine to read in the topographi! index image and set up at translation between the pixel number and the image row.and.& column.
Definition at line 1523 of file MODULE_IO.f90.
Referenced by rdtpmd().
subroutine module_io::rdatmo (integer i, type (grid_met_template), dimension(global%nrow*global%ncol), intent(inout) MET, type (global_template), intent(inout) GLOBAL, type (io_template), intent(in) IO)
Subroutine to read in and pass meteorological data (e.g. rainfall).
Definition at line 168 of file MODULE_IO.f90.
References rdforc().
Referenced by read_data().
subroutine module_io::rddata (type (global_template), intent(inout) GLOBAL, type (grid_template), dimension(:), allocatable GRID, type (regional_template) REG, type (catchment_template), dimension(:), allocatable CAT, type (io_template), intent(inout) IO)
Subroutine to open input/output files, read and initialize time in-variant data.
Definition at line 242 of file MODULE_IO.f90.
References inisim(), rdsoil(), rdtpmd(), and rdveg().
Referenced by initialize_model().
subroutine module_io::rdforc (real*8, dimension(:), intent(inout) pixdat, integer, intent(in) nrow, integer, intent(in) ncol, integer, dimension(:,:), intent(in) ipixnum, real, dimension(ncol,nrow), intent(in) data_in)
Subroutine to convert data to original setup.
Definition at line 221 of file MODULE_IO.f90.
Referenced by rdatmo().
subroutine module_io::rdimgi (integer, dimension(nrow*ncol) ia, integer iu, integer nrow, integer ncol, integer, dimension(nrow,ncol) ipixnum)
Subroutine to read in an image of integers and return an array of these values indexed by the soils-topographi! index pixel numbers.
Definition at line 1415 of file MODULE_IO.f90.
Referenced by rdsoil(), rdtpmd(), and rdveg().
subroutine module_io::rdimgr (real*8, dimension(nrow*ncol) a, integer iu, integer nrow, integer ncol, integer, dimension(nrow,ncol) ipixnum)
Subroutine to read in an image of 4 byte reals and return an array of these values indexed by the soils-topographic index pixel numbers.
Definition at line 1479 of file MODULE_IO.f90.
Referenced by rdtpmd().
subroutine module_io::rdsoil (type (global_template), intent(inout) GLOBAL, type (catchment_template), dimension(:), intent(inout), allocatable CAT, type (grid_template), dimension(:), intent(inout), allocatable GRID, type (io_template), intent(inout) IO)
Subroutine to read and initialize time in-variant soil parameters.
Definition at line 1187 of file MODULE_IO.f90.
References factln(), and rdimgi().
Referenced by rddata().
subroutine module_io::rdtpmd (type (grid_template), dimension(:), intent(inout), allocatable GRID, type (catchment_template), dimension(:), allocatable CAT, type (io_template), intent(inout) IO, type (global_template) GLOBAL)
Subroutine to read in and initialize topmodel parameters and the soils-topographic index map.
Definition at line 419 of file MODULE_IO.f90.
References rdatb(), rdimgi(), and rdimgr().
Referenced by rddata().
subroutine module_io::rdveg (type (global_template), intent(inout) GLOBAL, type (catchment_template), dimension(:), intent(inout), allocatable CAT, type (grid_template), dimension(:), intent(inout), allocatable GRID, type (regional_template), intent(inout) REG, type (io_template), intent(inout) IO)
Subroutine to read and initiailize simulation constant vegetation and land cover parameters.
Definition at line 730 of file MODULE_IO.f90.
References rdimgi().
Referenced by rddata().
subroutine module_io::rdveg_update (type (global_template), intent(inout) GLOBAL, type (grid_template), dimension(:), intent(inout) GRID)
Subroutine to update the vegetation parameters.
Definition at line 329 of file MODULE_IO.f90.
Referenced by read_data().
subroutine module_io::read_data (type (global_template), intent(inout) GLOBAL, type (grid_template), dimension(:), intent(inout), allocatable GRID, type (catchment_template), dimension(:), intent(inout), allocatable CAT, type (io_template), intent(inout) IO, integer, intent(in) i)
Subroutine to read in the model parameters.
Definition at line 84 of file MODULE_IO.f90.
References rdatmo(), and rdveg_update().
Referenced by toplats_driver().
subroutine module_io::read_general_file (type (global_template), intent(inout) GLOBAL)
Subroutine to read the general parameters file.
Definition at line 1630 of file MODULE_IO.f90.
Referenced by initialize_model().
subroutine module_io::write_binary (real*8, dimension(nrow*ncol) datain, real rmult, integer nrow, integer ncol, integer, dimension(nrow,ncol) ipixnum, integer i, type(global_template), intent(in) GLOBAL)
Subroutine to write raw binary data to the output file.
Definition at line 1122 of file MODULE_IO.f90.
Referenced by write_data().
subroutine module_io::write_data (type (global_template), intent(inout) GLOBAL, type (grid_template), dimension(:), intent(inout) GRID, type (io_template), intent(inout) IO, type (regional_template), intent(inout) REG, integer, intent(in) i)
Subroutine to output data to file.
Definition at line 123 of file MODULE_IO.f90.
References write_binary(), and write_regional().
Referenced by toplats_driver().
subroutine module_io::write_regional (integer, intent(in) i, type(regional_template), intent(in) REG, type(global_template), intent(in) GLOBAL)
subroutine to write regional variables to file
Definition at line 710 of file MODULE_IO.f90.
Referenced by write_data().
The documentation for this module was generated from the following file:
MODEL/MODULE_IO.f90