TOPLATS: fruit Module Reference
fruit Module Reference
Data Types
interface add_fail
interface addfail
interface addsuccess
interface assert_equals
interface assert_not_equals
interface assertequals
interface assertnotequals
interface asserttrue
interface case_failed_xml
interface case_passed_xml
interface end_override_stdout
interface fruit_finalize
interface fruit_summary_xml
interface get_case_name
interface get_messages
interface get_unit_name
interface getfailedcount
interface gettestsummary
interface gettotalcount
interface init_fruit_xml
interface initializefruit
interface isallsuccessful
interface override_stdout
interface run_test_case
interface runtestcase
interface set_case_name
interface set_unit_name
type ty_stack
Public Member Functions
subroutine, public init_fruit
subroutine, public fruit_summary
subroutine, public is_all_successful (result)
character(len=msg_length)
function, public get_last_message ()
subroutine, public get_total_count (count)
subroutine, public get_failed_count (count)
subroutine, public add_success
subroutine, public failed_assert_action (expected, got, message)
logical function, public is_last_passed ()
logical function, public is_case_passed ()
subroutine, public stash_test_suite
subroutine, public restore_test_suite
subroutine, public assert_true (var1, message)
Private Member Functions
subroutine fruit_finalize_
subroutine init_fruit_xml_
character(len=strlen_t) function case_delta_t ()
subroutine case_passed_xml_ (tc_name, classname)
subroutine case_failed_xml_ (tc_name, classname)
subroutine fruit_summary_xml_
character(len=number_length)
function int_to_str (i)
subroutine obsolete_initializefruit_
subroutine obsolete_gettestsummary_
subroutine run_test_case_named_ (tc, tc_name)
subroutine run_test_case_ (tc)
subroutine obsolete_addsuccess_
subroutine add_fail_ (message)
subroutine add_fail_unit_ (unitName, message)
subroutine obsolete_isallsuccessful_ (result)
subroutine output_mark_ (chr)
subroutine success_mark_
subroutine failed_mark_
subroutine increase_message_stack_
subroutine get_messages_ (msgs)
subroutine obsolete_gettotalcount_ (count)
subroutine obsolete_getfailedcount_ (count)
subroutine obsolete_ (message)
subroutine set_case_name_ (value)
subroutine get_case_name_ (value)
subroutine make_error_msg_ (var1, var2, message)
subroutine override_stdout_ (write_unit, filename)
subroutine end_override_stdout_
subroutine obsolete_assert_true_logical_ (var1, message)
subroutine assert_eq_logical_ (var1, var2, message)
subroutine assert_eq_1d_logical_ (var1, var2, n, message)
subroutine assert_eq_2d_logical_ (var1, var2, n, m, message)
subroutine assert_eq_string_ (var1, var2, message)
subroutine assert_eq_1d_string_ (var1, var2, n, message)
subroutine assert_eq_2d_string_ (var1, var2, n, m, message)
subroutine assert_eq_int_ (var1, var2, message)
subroutine assert_eq_1d_int_ (var1, var2, n, message)
subroutine assert_eq_2d_int_ (var1, var2, n, m, message)
subroutine assert_eq_real_ (var1, var2, message)
subroutine assert_eq_real_in_range_ (var1, var2, delta, message)
subroutine assert_eq_1d_real_ (var1, var2, n, message)
subroutine assert_eq_1d_real_in_range_ (var1, var2, n, delta, message)
subroutine assert_eq_2d_real_ (var1, var2, n, m, message)
subroutine assert_eq_2d_real_in_range_ (var1, var2, n, m, delta, message)
subroutine assert_eq_double_ (var1, var2, message)
subroutine assert_eq_double_in_range_ (var1, var2, delta, message)
subroutine assert_eq_1d_double_ (var1, var2, n, message)
subroutine assert_eq_1d_double_in_range_ (var1, var2, n, delta, message)
subroutine assert_eq_2d_double_ (var1, var2, n, m, message)
subroutine assert_eq_2d_double_in_range_ (var1, var2, n, m, delta, message)
subroutine assert_eq_complex_ (var1, var2, message)
subroutine assert_eq_complex_in_range_ (var1, var2, delta, message)
subroutine assert_eq_1d_complex_ (var1, var2, n, message)
subroutine assert_eq_1d_complex_in_range_ (var1, var2, n, delta, message)
subroutine assert_eq_2d_complex_ (var1, var2, n, m, message)
subroutine assert_eq_2d_complex_in_range_ (var1, var2, n, m, delta, message)
subroutine assert_not_equals_logical_ (var1, var2, message)
subroutine assert_not_equals_1d_logical_ (var1, var2, n, message)
subroutine assert_not_equals_2d_logical_ (var1, var2, n, m, message)
subroutine assert_not_equals_string_ (var1, var2, message)
subroutine assert_not_equals_1d_string_ (var1, var2, n, message)
subroutine assert_not_equals_2d_string_ (var1, var2, n, m, message)
subroutine assert_not_equals_int_ (var1, var2, message)
subroutine assert_not_equals_1d_int_ (var1, var2, n, message)
subroutine assert_not_equals_2d_int_ (var1, var2, n, m, message)
subroutine assert_not_equals_real_ (var1, var2, message)
subroutine assert_not_equals_real_in_range_ (var1, var2, delta, message)
subroutine assert_not_equals_1d_real_ (var1, var2, n, message)
subroutine assert_not_equals_1d_real_in_range_ (var1, var2, n, delta, message)
subroutine assert_not_equals_2d_real_ (var1, var2, n, m, message)
subroutine assert_not_equals_2d_real_in_range_ (var1, var2, n, m, delta, message)
subroutine assert_not_equals_double_ (var1, var2, message)
subroutine assert_not_equals_double_in_range_ (var1, var2, delta, message)
subroutine assert_not_equals_1d_double_ (var1, var2, n, message)
subroutine assert_not_equals_1d_double_in_range_ (var1, var2, n, delta, message)
subroutine assert_not_equals_2d_double_ (var1, var2, n, m, message)
subroutine assert_not_equals_2d_double_in_range_ (var1, var2, n, m, delta, message)
subroutine assert_not_equals_complex_ (var1, var2, message)
subroutine assert_not_equals_complex_in_range_ (var1, var2, delta, message)
subroutine assert_not_equals_1d_complex_ (var1, var2, n, message)
subroutine assert_not_equals_1d_complex_in_range_ (var1, var2, n, delta, message)
subroutine assert_not_equals_2d_complex_ (var1, var2, n, m, message)
subroutine assert_not_equals_2d_complex_in_range_ (var1, var2, n, m, delta, message)
Private Attributes
integer, parameter stdout_default = 6
integer stdout = STDOUT_DEFAULT
integer, parameter xml_open = 20
integer, parameter xml_work = 21
integer, parameter number_length = 10
character(len=*), parameter xml_filename = "result.xml"
character(len=*), parameter xml_filename_work = "result_tmp.xml"
integer, parameter msg_length = 256
integer, parameter max_msg_stack_size = 2000
integer, parameter msg_array_increment = 50
integer, parameter max_marks_per_line = 78
character(*), parameter default_case_name = '_not_set_'
integer, save, private successful_assert_count = 0
integer, save, private failed_assert_count = 0
integer, save, private message_index = 1
integer, save, private message_index_from = 1
integer, save, private current_max = 50
character(len=msg_length),
dimension(:), allocatable,
private message_array
character(len=msg_length),
save, private msg = '[unit name not set from set_name]: '
character(len=msg_length),
save, private case_name = DEFAULT_CASE_NAME
integer, save, private successful_case_count = 0
integer, save, private failed_case_count = 0
integer, save, private testcaseindex = 1
logical, save, private last_passed = .false.
logical, save, private case_passed = .false.
integer, save, private case_time_from = 0
integer, save, private linechar_count = 0
type(ty_stack), save stashed_suite
Detailed Description
Definition at line 18 of file fruit.f90.
Member Function/Subroutine Documentation
subroutine fruit::add_fail_ (character (*), intent(in), optional message) private
Definition at line 568 of file fruit.f90.
References failed_assert_action().
subroutine fruit::add_fail_unit_ (character (*), intent(in) unitName, character (*), intent(in) message) private
Definition at line 573 of file fruit.f90.
References fruit::add_fail::add_fail_().
subroutine, public fruit::add_success ()
Definition at line 699 of file fruit.f90.
References success_mark_().
Referenced by assert_eq_1d_complex_(), assert_eq_1d_complex_in_range_(), assert_eq_1d_double_(), assert_eq_1d_double_in_range_(), assert_eq_1d_int_(), assert_eq_1d_logical_(), assert_eq_1d_real_(), assert_eq_1d_real_in_range_(), assert_eq_1d_string_(), assert_eq_2d_complex_(), assert_eq_2d_complex_in_range_(), assert_eq_2d_double_(), assert_eq_2d_double_in_range_(), assert_eq_2d_int_(), assert_eq_2d_logical_(), assert_eq_2d_real_(), assert_eq_2d_real_in_range_(), assert_eq_2d_string_(), assert_eq_complex_(), assert_eq_complex_in_range_(), assert_eq_double_(), assert_eq_double_in_range_(), assert_eq_int_(), assert_eq_logical_(), assert_eq_real_(), assert_eq_real_in_range_(), assert_eq_string_(), assert_not_equals_1d_complex_(), assert_not_equals_1d_complex_in_range_(), assert_not_equals_1d_double_(), assert_not_equals_1d_double_in_range_(), assert_not_equals_1d_int_(), assert_not_equals_1d_logical_(), assert_not_equals_1d_real_(), assert_not_equals_1d_real_in_range_(), assert_not_equals_1d_string_(), assert_not_equals_2d_complex_(), assert_not_equals_2d_complex_in_range_(), assert_not_equals_2d_double_(), assert_not_equals_2d_double_in_range_(), assert_not_equals_2d_int_(), assert_not_equals_2d_logical_(), assert_not_equals_2d_real_(), assert_not_equals_2d_real_in_range_(), assert_not_equals_2d_string_(), assert_not_equals_complex_(), assert_not_equals_complex_in_range_(), assert_not_equals_double_(), assert_not_equals_double_in_range_(), assert_not_equals_int_(), assert_not_equals_logical_(), assert_not_equals_real_(), assert_not_equals_real_in_range_(), assert_not_equals_string_(), assert_true(), and obsolete_addsuccess_().
subroutine fruit::assert_eq_1d_complex_ (complex(kind=kind(1.0d0)), dimension(n), intent(in) var1, complex(kind=kind(1.0d0)), dimension(n), intent(in) var2, integer, intent(in) n, character(len = *), intent(in), optional message) private
Definition at line 1268 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_1d_complex_in_range_ (complex(kind=kind(1.0d0)), dimension(n), intent(in) var1, complex(kind=kind(1.0d0)), dimension(n), intent(in) var2, integer, intent(in) n, double precision, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1286 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_1d_double_ (double precision, dimension(n), intent(in) var1, double precision, dimension(n), intent(in) var2, integer, intent(in) n, character(len = *), intent(in), optional message) private
Definition at line 1158 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_1d_double_in_range_ (double precision, dimension(n), intent(in) var1, double precision, dimension(n), intent(in) var2, integer, intent(in) n, double precision, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1176 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_1d_int_ (integer, dimension(n), intent(in) var1, integer, dimension(n), intent(in) var2, integer, intent(in) n, character(len = *), intent(in), optional message) private
Definition at line 976 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_1d_logical_ (logical, dimension(n), intent(in) var1, logical, dimension(n), intent(in) var2, integer, intent(in) n, character(len = *), intent(in), optional message) private
Definition at line 866 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_1d_real_ (real, dimension(n), intent(in) var1, real, dimension(n), intent(in) var2, integer, intent(in) n, character(len = *), intent(in), optional message) private
Definition at line 1048 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_1d_real_in_range_ (real, dimension(n), intent(in) var1, real, dimension(n), intent(in) var2, integer, intent(in) n, real, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1066 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_1d_string_ (character (len = *), dimension(n), intent(in) var1, character (len = *), dimension(n), intent(in) var2, integer, intent(in) n, character(len = *), intent(in), optional message) private
Definition at line 921 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_2d_complex_ (complex(kind=kind(1.0d0)), dimension(n, m), intent(in) var1, complex(kind=kind(1.0d0)), dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, character(len = *), intent(in), optional message) private
Definition at line 1304 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_2d_complex_in_range_ (complex(kind=kind(1.0d0)), dimension(n, m), intent(in) var1, complex(kind=kind(1.0d0)), dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, double precision, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1324 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_2d_double_ (double precision, dimension(n, m), intent(in) var1, double precision, dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, character(len = *), intent(in), optional message) private
Definition at line 1194 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_2d_double_in_range_ (double precision, dimension(n, m), intent(in) var1, double precision, dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, double precision, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1214 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_2d_int_ (integer, dimension(n, m), intent(in) var1, integer, dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, character(len = *), intent(in), optional message) private
Definition at line 994 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_2d_logical_ (logical, dimension(n, m), intent(in) var1, logical, dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, character(len = *), intent(in), optional message) private
Definition at line 884 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_2d_real_ (real, dimension(n, m), intent(in) var1, real, dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, character(len = *), intent(in), optional message) private
Definition at line 1084 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_2d_real_in_range_ (real, dimension(n, m), intent(in) var1, real, dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, real, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1104 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_2d_string_ (character (len = *), dimension(n, m), intent(in) var1, character (len = *), dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, character(len = *), intent(in), optional message) private
Definition at line 939 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_complex_ (complex(kind=kind(1.0d0)), intent(in) var1, complex(kind=kind(1.0d0)), intent(in) var2, character(len = *), intent(in), optional message) private
Definition at line 1234 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_complex_in_range_ (complex(kind=kind(1.0d0)), intent(in) var1, complex(kind=kind(1.0d0)), intent(in) var2, double precision, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1251 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_double_ (double precision, intent(in) var1, double precision, intent(in) var2, character(len = *), intent(in), optional message) private
Definition at line 1124 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_double_in_range_ (double precision, intent(in) var1, double precision, intent(in) var2, double precision, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1141 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_int_ (integer, intent(in) var1, integer, intent(in) var2, character(len = *), intent(in), optional message) private
Definition at line 959 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_logical_ (logical, intent(in) var1, logical, intent(in) var2, character(len = *), intent(in), optional message) private
Definition at line 849 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_real_ (real, intent(in) var1, real, intent(in) var2, character(len = *), intent(in), optional message) private
Definition at line 1014 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_real_in_range_ (real, intent(in) var1, real, intent(in) var2, real, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1031 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_eq_string_ (character (len = *), intent(in) var1, character (len = *), intent(in) var2, character(len = *), intent(in), optional message) private
Definition at line 904 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_1d_complex_ (complex(kind=kind(1.0d0)), dimension(n), intent(in) var1, complex(kind=kind(1.0d0)), dimension(n), intent(in) var2, integer, intent(in) n, character(len = *), intent(in), optional message) private
Definition at line 1901 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_1d_complex_in_range_ (complex(kind=kind(1.0d0)), dimension(n), intent(in) var1, complex(kind=kind(1.0d0)), dimension(n), intent(in) var2, integer, intent(in) n, double precision, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1925 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_1d_double_ (double precision, dimension(n), intent(in) var1, double precision, dimension(n), intent(in) var2, integer, intent(in) n, character(len = *), intent(in), optional message) private
Definition at line 1755 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_1d_double_in_range_ (double precision, dimension(n), intent(in) var1, double precision, dimension(n), intent(in) var2, integer, intent(in) n, double precision, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1779 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_1d_int_ (integer, dimension(n), intent(in) var1, integer, dimension(n), intent(in) var2, integer, intent(in) n, character(len = *), intent(in), optional message) private
Definition at line 1513 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_1d_logical_ (logical, dimension(n), intent(in) var1, logical, dimension(n), intent(in) var2, integer, intent(in) n, character(len = *), intent(in), optional message) private
Definition at line 1367 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_1d_real_ (real, dimension(n), intent(in) var1, real, dimension(n), intent(in) var2, integer, intent(in) n, character(len = *), intent(in), optional message) private
Definition at line 1609 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_1d_real_in_range_ (real, dimension(n), intent(in) var1, real, dimension(n), intent(in) var2, integer, intent(in) n, real, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1633 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_1d_string_ (character (len = *), dimension(n), intent(in) var1, character (len = *), dimension(n), intent(in) var2, integer, intent(in) n, character(len = *), intent(in), optional message) private
Definition at line 1440 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_2d_complex_ (complex(kind=kind(1.0d0)), dimension(n, m), intent(in) var1, complex(kind=kind(1.0d0)), dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, character(len = *), intent(in), optional message) private
Definition at line 1949 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_2d_complex_in_range_ (complex(kind=kind(1.0d0)), dimension(n, m), intent(in) var1, complex(kind=kind(1.0d0)), dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, double precision, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1975 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_2d_double_ (double precision, dimension(n, m), intent(in) var1, double precision, dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, character(len = *), intent(in), optional message) private
Definition at line 1803 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_2d_double_in_range_ (double precision, dimension(n, m), intent(in) var1, double precision, dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, double precision, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1829 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_2d_int_ (integer, dimension(n, m), intent(in) var1, integer, dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, character(len = *), intent(in), optional message) private
Definition at line 1537 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_2d_logical_ (logical, dimension(n, m), intent(in) var1, logical, dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, character(len = *), intent(in), optional message) private
Definition at line 1391 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_2d_real_ (real, dimension(n, m), intent(in) var1, real, dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, character(len = *), intent(in), optional message) private
Definition at line 1657 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_2d_real_in_range_ (real, dimension(n, m), intent(in) var1, real, dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, real, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1683 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_2d_string_ (character (len = *), dimension(n, m), intent(in) var1, character (len = *), dimension(n, m), intent(in) var2, integer, intent(in) n, integer, intent(in) m, character(len = *), intent(in), optional message) private
Definition at line 1464 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_complex_ (complex(kind=kind(1.0d0)), intent(in) var1, complex(kind=kind(1.0d0)), intent(in) var2, character(len = *), intent(in), optional message) private
Definition at line 1855 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_complex_in_range_ (complex(kind=kind(1.0d0)), intent(in) var1, complex(kind=kind(1.0d0)), intent(in) var2, double precision, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1878 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_double_ (double precision, intent(in) var1, double precision, intent(in) var2, character(len = *), intent(in), optional message) private
Definition at line 1709 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_double_in_range_ (double precision, intent(in) var1, double precision, intent(in) var2, double precision, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1732 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_int_ (integer, intent(in) var1, integer, intent(in) var2, character(len = *), intent(in), optional message) private
Definition at line 1490 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_logical_ (logical, intent(in) var1, logical, intent(in) var2, character(len = *), intent(in), optional message) private
Definition at line 1344 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_real_ (real, intent(in) var1, real, intent(in) var2, character(len = *), intent(in), optional message) private
Definition at line 1563 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_real_in_range_ (real, intent(in) var1, real, intent(in) var2, real, intent(in) delta, character(len = *), intent(in), optional message) private
Definition at line 1586 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine fruit::assert_not_equals_string_ (character (len = *), intent(in) var1, character (len = *), intent(in) var2, character(len = *), intent(in), optional message) private
Definition at line 1417 of file fruit.f90.
References add_success(), and failed_assert_action().
subroutine, public fruit::assert_true (logical, intent(in) var1, character (*), intent(in), optional message)
Definition at line 836 of file fruit.f90.
References add_success(), and failed_assert_action().
Referenced by obsolete_assert_true_logical_().
character(len = strlen_t) function fruit::case_delta_t () private
Definition at line 367 of file fruit.f90.
Referenced by case_failed_xml_(), and case_passed_xml_().
subroutine fruit::case_failed_xml_ (character(*), intent(in) tc_name, character(*), intent(in) classname) private
Definition at line 398 of file fruit.f90.
References case_delta_t().
subroutine fruit::case_passed_xml_ (character(*), intent(in) tc_name, character(*), intent(in) classname) private
Definition at line 387 of file fruit.f90.
References case_delta_t().
subroutine fruit::end_override_stdout_ () private
Definition at line 820 of file fruit.f90.
subroutine, public fruit::failed_assert_action (character(*), intent(in) expected, character(*), intent(in) got, character(*), intent(in), optional message)
Definition at line 706 of file fruit.f90.
References failed_mark_(), increase_message_stack_(), and make_error_msg_().
Referenced by add_fail_(), assert_eq_1d_complex_(), assert_eq_1d_complex_in_range_(), assert_eq_1d_double_(), assert_eq_1d_double_in_range_(), assert_eq_1d_int_(), assert_eq_1d_logical_(), assert_eq_1d_real_(), assert_eq_1d_real_in_range_(), assert_eq_1d_string_(), assert_eq_2d_complex_(), assert_eq_2d_complex_in_range_(), assert_eq_2d_double_(), assert_eq_2d_double_in_range_(), assert_eq_2d_int_(), assert_eq_2d_logical_(), assert_eq_2d_real_(), assert_eq_2d_real_in_range_(), assert_eq_2d_string_(), assert_eq_complex_(), assert_eq_complex_in_range_(), assert_eq_double_(), assert_eq_double_in_range_(), assert_eq_int_(), assert_eq_logical_(), assert_eq_real_(), assert_eq_real_in_range_(), assert_eq_string_(), assert_not_equals_1d_complex_(), assert_not_equals_1d_complex_in_range_(), assert_not_equals_1d_double_(), assert_not_equals_1d_double_in_range_(), assert_not_equals_1d_int_(), assert_not_equals_1d_logical_(), assert_not_equals_1d_real_(), assert_not_equals_1d_real_in_range_(), assert_not_equals_1d_string_(), assert_not_equals_2d_complex_(), assert_not_equals_2d_complex_in_range_(), assert_not_equals_2d_double_(), assert_not_equals_2d_double_in_range_(), assert_not_equals_2d_int_(), assert_not_equals_2d_logical_(), assert_not_equals_2d_real_(), assert_not_equals_2d_real_in_range_(), assert_not_equals_2d_string_(), assert_not_equals_complex_(), assert_not_equals_complex_in_range_(), assert_not_equals_double_(), assert_not_equals_double_in_range_(), assert_not_equals_int_(), assert_not_equals_logical_(), assert_not_equals_real_(), assert_not_equals_real_in_range_(), assert_not_equals_string_(), and assert_true().
subroutine fruit::failed_mark_ () private
Definition at line 612 of file fruit.f90.
References output_mark_().
Referenced by failed_assert_action().
subroutine fruit::fruit_finalize_ () private
Definition at line 352 of file fruit.f90.
subroutine, public fruit::fruit_summary ()
Definition at line 518 of file fruit.f90.
Referenced by catchment_tests_driver(), obsolete_gettestsummary_(), and module_unit_tests::run_unit_tests().
subroutine fruit::fruit_summary_xml_ () private
Definition at line 424 of file fruit.f90.
References int_to_str().
subroutine fruit::get_case_name_ (character(*), intent(out) value) private
Definition at line 723 of file fruit.f90.
subroutine, public fruit::get_failed_count (integer, intent(out) count)
Definition at line 680 of file fruit.f90.
Referenced by obsolete_getfailedcount_().
character(len=msg_length) function, public fruit::get_last_message ()
Definition at line 639 of file fruit.f90.
subroutine fruit::get_messages_ (character(len = *), dimension(:), intent(out) msgs) private
Definition at line 648 of file fruit.f90.
subroutine, public fruit::get_total_count (integer, intent(out) count)
Definition at line 666 of file fruit.f90.
Referenced by obsolete_gettotalcount_().
subroutine fruit::increase_message_stack_ () private
Definition at line 616 of file fruit.f90.
Referenced by failed_assert_action().
subroutine, public fruit::init_fruit ()
Definition at line 336 of file fruit.f90.
Referenced by catchment_tests_driver(), obsolete_initializefruit_(), and module_unit_tests::run_unit_tests().
subroutine fruit::init_fruit_xml_ () private
Definition at line 358 of file fruit.f90.
character(len = number_length) function fruit::int_to_str (integer, intent(in) i) private
Definition at line 450 of file fruit.f90.
Referenced by fruit_summary_xml_().
subroutine, public fruit::is_all_successful (logical, intent(out) result)
Definition at line 586 of file fruit.f90.
logical function, public fruit::is_case_passed ()
Definition at line 743 of file fruit.f90.
logical function, public fruit::is_last_passed ()
Definition at line 738 of file fruit.f90.
subroutine fruit::make_error_msg_ (character(*), intent(in) var1, character(*), intent(in) var2, character(*), intent(in), optional message) private
Definition at line 728 of file fruit.f90.
Referenced by failed_assert_action().
subroutine fruit::obsolete_ (character (*), intent(in), optional message) private
Definition at line 685 of file fruit.f90.
Referenced by obsolete_addsuccess_(), obsolete_assert_true_logical_(), obsolete_getfailedcount_(), obsolete_gettestsummary_(), obsolete_gettotalcount_(), obsolete_initializefruit_(), and obsolete_isallsuccessful_().
subroutine fruit::obsolete_addsuccess_ () private
Definition at line 563 of file fruit.f90.
References add_success(), and obsolete_().
subroutine fruit::obsolete_assert_true_logical_ (logical, intent(in) var1, character (*), intent(in), optional message) private
Definition at line 828 of file fruit.f90.
References assert_true(), and obsolete_().
subroutine fruit::obsolete_getfailedcount_ (integer, intent(out) count) private
Definition at line 672 of file fruit.f90.
References get_failed_count(), and obsolete_().
subroutine fruit::obsolete_gettestsummary_ () private
Definition at line 463 of file fruit.f90.
References fruit_summary(), and obsolete_().
subroutine fruit::obsolete_gettotalcount_ (integer, intent(out) count) private
Definition at line 660 of file fruit.f90.
References get_total_count(), and obsolete_().
subroutine fruit::obsolete_initializefruit_ () private
Definition at line 458 of file fruit.f90.
References init_fruit(), and obsolete_().
subroutine fruit::obsolete_isallsuccessful_ (logical, intent(out) result) private
Definition at line 580 of file fruit.f90.
References obsolete_().
subroutine fruit::output_mark_ (character(1), intent(in) chr) private
Definition at line 592 of file fruit.f90.
Referenced by failed_mark_(), and success_mark_().
subroutine fruit::override_stdout_ (integer, intent(in) write_unit, character(len = *), intent(in) filename) private
Definition at line 748 of file fruit.f90.
subroutine, public fruit::restore_test_suite ()
Definition at line 795 of file fruit.f90.
subroutine fruit::run_test_case_ (tc) private
Definition at line 508 of file fruit.f90.
References fruit::run_test_case::run_test_case_named_().
subroutine fruit::run_test_case_named_ (tc, character(*), intent(in) tc_name) private
Definition at line 469 of file fruit.f90.
subroutine fruit::set_case_name_ (character(*), intent(in) value) private
Definition at line 718 of file fruit.f90.
subroutine, public fruit::stash_test_suite ()
Definition at line 756 of file fruit.f90.
subroutine fruit::success_mark_ () private
Definition at line 608 of file fruit.f90.
References output_mark_().
Referenced by add_success().
Member Data Documentation
character (len = msg_length), save, private fruit::case_name = DEFAULT_CASE_NAME private
Definition at line 50 of file fruit.f90.
logical, save, private fruit::case_passed = .false. private
Definition at line 56 of file fruit.f90.
integer, save, private fruit::case_time_from = 0 private
Definition at line 57 of file fruit.f90.
integer, save, private fruit::current_max = 50 private
Definition at line 46 of file fruit.f90.
character(*), parameter fruit::default_case_name = '_not_set_' private
Definition at line 38 of file fruit.f90.
integer, save, private fruit::failed_assert_count = 0 private
Definition at line 42 of file fruit.f90.
integer, save, private fruit::failed_case_count = 0 private
Definition at line 53 of file fruit.f90.
logical, save, private fruit::last_passed = .false. private
Definition at line 55 of file fruit.f90.
integer, save, private fruit::linechar_count = 0 private
Definition at line 58 of file fruit.f90.
integer, parameter fruit::max_marks_per_line = 78 private
Definition at line 36 of file fruit.f90.
integer, parameter fruit::max_msg_stack_size = 2000 private
Definition at line 34 of file fruit.f90.
character (len = msg_length), dimension(:), allocatable, private fruit::message_array private
Definition at line 48 of file fruit.f90.
integer, save, private fruit::message_index = 1 private
Definition at line 44 of file fruit.f90.
integer, save, private fruit::message_index_from = 1 private
Definition at line 45 of file fruit.f90.
character (len = msg_length), save, private fruit::msg = '[unit name not set from set_name]: ' private
Definition at line 49 of file fruit.f90.
integer, parameter fruit::msg_array_increment = 50 private
Definition at line 35 of file fruit.f90.
integer, parameter fruit::msg_length = 256 private
Definition at line 33 of file fruit.f90.
integer, parameter fruit::number_length = 10 private
Definition at line 28 of file fruit.f90.
type(ty_stack), save fruit::stashed_suite private
Definition at line 81 of file fruit.f90.
integer fruit::stdout = STDOUT_DEFAULT private
Definition at line 24 of file fruit.f90.
integer, parameter fruit::stdout_default = 6 private
Definition at line 23 of file fruit.f90.
integer, save, private fruit::successful_assert_count = 0 private
Definition at line 41 of file fruit.f90.
integer, save, private fruit::successful_case_count = 0 private
Definition at line 52 of file fruit.f90.
integer, save, private fruit::testcaseindex = 1 private
Definition at line 54 of file fruit.f90.
character (len = *), parameter fruit::xml_filename = "result.xml" private
Definition at line 30 of file fruit.f90.
character (len = *), parameter fruit::xml_filename_work = "result_tmp.xml" private
Definition at line 31 of file fruit.f90.
integer, parameter fruit::xml_open = 20 private
Definition at line 26 of file fruit.f90.
integer, parameter fruit::xml_work = 21 private
Definition at line 27 of file fruit.f90.
The documentation for this module was generated from the following file:
TESTS/fruit/fruit.f90