module_shared Module Reference
module_shared Module Reference
Public Member Functions
subroutine soiladapt (iopgveg, thermc, iopthermc_v, tcbeta, xlai, thermc1, heatcap, heatcap1, zero)
Adapt the thermal parameters for vegetated surfaces.
subroutine soiltherm (iopthermc, thermc1, thermc2, rzsm, smtmp, thetar, thetas, psic, bcbeta, tkmid, quartz, ifcoarse, heatcap1, heatcap2, heatcapold, rocpsoil, row, cph2o, roa, cp, roi, smold, thermc, heatcap, inc_frozen, rzdthetaudtemp)
Calculate the soil thermal parameters.
subroutine sm_cen_dif (iffroz, tkmid, zmid, zrzmax, smtmp, rzsm, tzsm, smold, rzsmold, tzsmold)
Initialize soil moisture for the calculation of the thermodynami parameters, as a centered difference.
subroutine calc_rs (GRID_VEG, i_und, i_moss, Swq_us, alb_moss, alb_snow, rsd, rs_over, rs_under)
Calculate the incoming solar radiation for the under and over story under the assumption of only one reflection.
function calchc (theta, thetasat, rocp, row, cph2o, roa, cp, temperature, roi, inc_frozen, rzdthetaudtemp)
Calculate the heat capacity of the soil using the input soil moisture requested (theta), and saturated soil moisture or porosity (thetasat). Heat capacity found as density-weighted combination of soil, water and air heat capacities.
subroutine stabcor (zwind, zhum, wind_s, zpdis, r_m, tair, airp, t_skin, vappres, richn)
Subroutine to calculate all variables related to stability correction and aerodynami! resistances.
real *8 function calcrib (tk2, q2, p2, u2, z2, tk1, q1)
Calculate Bulk Richardson number based on input temperature, humidity, pressure, wind profile.
function calctc_j (theta, thetar, thetas, quartz, iffrozen, ifcoarse)
function calctc_m (soilm, thetar, thetas, psic, bcbeta)
subroutine nreb (ipetopt, alb, emiss, thermc1, thermc2, heatcap1, heatcap2, heatcapold, rav, rah, tskink, tmidk, rn, xle, epot, h, g, ds, tairc, vppa, roa, psychr, xlhv, zdeep, tdeep, zmid, rsd, rld, toleb, maxnri, dt, itime)
subroutine nreb_snow (thermc1, thermc2, heatcap1, heatcap2, heatcapold, tskink, tmidknew, tairc, zdeep, tdeep, zmid, dt, gtmp)
function calcra (uzw, zw, za, zpd, z0m, z0h, rib)
Detailed Description
Definition at line 1 of file MODULE_SHARED.f90.
Member Function/Subroutine Documentation
subroutine module_shared::calc_rs (type (grid_veg_template) GRID_VEG, i_und, i_moss, Swq_us, alb_moss, alb_snow, rsd, rs_over, rs_under)
Calculate the incoming solar radiation for the under and over story under the assumption of only one reflection.
Definition at line 216 of file MODULE_SHARED.f90.
References alb_moss, alb_snow, ccc, d0, i_und, refus, rs_over, rs_under, and rsd.
Referenced by module_unit_tests::calc_rs_test1(), module_unit_tests::calc_rs_test2(), module_land::land(), and module_atmos::peteb().
function module_shared::calchc (theta, thetasat, rocp, row, cph2o, roa, cp, temperature, roi, inc_frozen, rzdthetaudtemp)
Calculate the heat capacity of the soil using the input soil moisture requested (theta), and saturated soil moisture or porosity (thetasat). Heat capacity found as density-weighted combination of soil, water and air heat capacities.
Definition at line 279 of file MODULE_SHARED.f90.
References cp, cph2o, d0, heatcap, inc_frozen, roa, rocp, roi, row, rzdthetaudtemp, temperature, theta, thetasat, and ttt.
Referenced by soiltherm().
function module_shared::calcra (uzw, zw, za, zpd, z0m, z0h, rib)
Definition at line 1221 of file MODULE_SHARED.f90.
References astab, d0, one, resist, rib, stcorr, two, uzw, vkc, vkctwo, z0h, z0m, za, zero, zpd, and zw.
Referenced by module_atmos::atmos(), module_unit_tests::calcra_test1(), module_unit_tests::calcra_test2(), module_land::ebsres(), and module_atmos::peteb_wv().
real*8 function module_shared::calcrib (tk2, q2, p2, u2, z2, tk1, q1)
Calculate Bulk Richardson number based on input temperature, humidity, pressure, wind profile.
Definition at line 516 of file MODULE_SHARED.f90.
References d0, p2, q1, q2, rdcp, thta1, thta1v, thta2, thta2v, tk1, tk2, u2, and z2.
Referenced by module_unit_tests::calcrib_test1(), module_unit_tests::calcrib_test2(), and stabcor().
function module_shared::calctc_j (theta, thetar, thetas, quartz, iffrozen, ifcoarse)
Definition at line 584 of file MODULE_SHARED.f90.
References bulkdens, d0, ifcoarse, iffrozen, kdry, ko, ks, ksat, quartz, satrel, soildens, thermc, theta, thetar, and thetas.
Referenced by soiltherm().
function module_shared::calctc_m (soilm, thetar, thetas, psic, bcbeta)
Definition at line 740 of file MODULE_SHARED.f90.
References bcbeta, d0, pf, psi, psic, psicm, satrel, soilm, thermc, thetar, thetas, and tmpthermc.
Referenced by soiltherm().
subroutine module_shared::nreb (ipetopt, alb, emiss, thermc1, thermc2, heatcap1, heatcap2, heatcapold, rav, rah, tskink, tmidk, rn, xle, epot, h, g, ds, tairc, vppa, roa, psychr, xlhv, zdeep, tdeep, zmid, rsd, rld, toleb, maxnri, dt, itime)
Definition at line 792 of file MODULE_SHARED.f90.
References alb, astab, cp, cph2o, d(), d0, ddsdt, deltnr, dftdt, dftfac, dgdt, dhdt, drndt, ds, dsold, dstmp, dt, dxledt, dzdeep, emiss, epot, four, ft, g, gdenom, gtmp, h, heatcap1, heatcap2, heatcapold, htmp, iconv, ihflg, ileflg, ipetopt, iter, itime, itmpflg, maxnri, one, psychr, rah, rav, rld, rn, rntmp, roa, row, rsd, sbc, tairc, tdeep, thermc1, thermc2, three, tmidk, tmidknew, toldmidk, toleb, tskinc, tskink, two, vkc, vpdef, vppa, vpsat, xle, xletmp, xlhv, zdeep, and zmid.
Referenced by module_land::ebsres(), module_land::engact(), module_atmos::peteb_bs(), module_atmos::peteb_dv(), and module_atmos::peteb_wv().
subroutine module_shared::nreb_snow (thermc1, thermc2, heatcap1, heatcap2, heatcapold, tskink, tmidknew, tairc, zdeep, tdeep, zmid, dt, gtmp)
Definition at line 1146 of file MODULE_SHARED.f90.
References d0, dt, dzdeep, gdenom, gtmp, heatcap1, heatcap2, heatcapold, tairc, tdeep, thermc1, thermc2, tmidk, tmidknew, tskink, zdeep, and zmid.
Referenced by module_land::land(), module_land::land_os(), module_unit_tests::nreb_snow_test1(), module_unit_tests::nreb_snow_test2(), module_atmos::peteb_bs(), module_atmos::peteb_dv(), and module_atmos::peteb_wv().
subroutine module_shared::sm_cen_dif (iffroz, tkmid, zmid, zrzmax, smtmp, rzsm, tzsm, smold, rzsmold, tzsmold)
Initialize soil moisture for the calculation of the thermodynami parameters, as a centered difference.
Definition at line 179 of file MODULE_SHARED.f90.
References iffroz, rzsm, rzsmold, smold, smtmp, tkmid, tzsm, tzsmold, zmid, and zrzmax.
Referenced by module_land::ebsres(), module_land::engact(), module_land::land(), module_atmos::peteb(), module_unit_tests::sm_cen_dif_test1(), and module_unit_tests::sm_cen_dif_test2().
subroutine module_shared::soiladapt (iopgveg, thermc, iopthermc_v, tcbeta, xlai, thermc1, heatcap, heatcap1, zero)
Adapt the thermal parameters for vegetated surfaces.
Definition at line 21 of file MODULE_SHARED.f90.
References d0, heatcap, heatcap1, iopgveg, iopthermc_v, tcbeta, thermc, thermc1, xlai, and zero.
Referenced by module_land::engact(), module_land::land(), module_atmos::peteb(), module_unit_tests::soiladapt_test1(), and module_unit_tests::soiladapt_test2().
subroutine module_shared::soiltherm (iopthermc, thermc1, thermc2, rzsm, smtmp, thetar, thetas, psic, bcbeta, tkmid, quartz, ifcoarse, heatcap1, heatcap2, heatcapold, rocpsoil, row, cph2o, roa, cp, roi, smold, thermc, heatcap, inc_frozen, rzdthetaudtemp)
Calculate the soil thermal parameters.
Definition at line 111 of file MODULE_SHARED.f90.
References bcbeta, calchc(), calctc_j(), calctc_m(), cp, cph2o, heatcap, heatcap1, heatcap2, heatcapold, ifcoarse, iffroz, inc_frozen, iopthermc, psic, quartz, roa, rocpsoil, roi, row, rzdthetaudtemp, rzsm, smold, smtmp, thermc, thermc1, thermc2, thetar, thetas, and tkmid.
Referenced by module_land::ebsres(), module_land::engact(), module_land::land(), and module_atmos::peteb().
subroutine module_shared::stabcor (zwind, zhum, wind_s, zpdis, r_m, tair, airp, t_skin, vappres, richn)
Subroutine to calculate all variables related to stability correction and aerodynami! resistances.
Definition at line 430 of file MODULE_SHARED.f90.
References appa, calcrib(), d0, qskin, qv, r_m, richn, t_skin, tair, uza, vappres, wind_s, zhum, zpdis, and zwind.
Referenced by module_atmos::atmos(), module_land::ebsres(), module_atmos::peteb_wv(), module_unit_tests::stabcor_test1(), and module_unit_tests::stabcor_test2().
The documentation for this module was generated from the following file:
MODEL/MODULE_SHARED.f90