module_atmos Module Reference
module_atmos Module Reference
Public Member Functions
subroutine atmos (ipix, i, dt, inc_frozen, i_2l,
subroutine inittk (GRID_SOIL, GRID_VEG, GRID_VARS, tdeep, tmid0, tmid0_moss, tkmid, tkmid_us, tkmid_moss, tkel, tk0moss, tkact, tkact_us, tkact_moss, tskinact_moss, dshact, dshact_us, dshact_moss, tkpet, tkmidpet, tkmidpet_us, tkmidpet_moss, dspet, dspet_us, dspet_moss, Tsurf, Tpack, Tsurf_us, Tpack_us)
subroutine petpen (GRID_VEG, GRID_MET, GRID_VARS, tcel, vpsat, vpdef, f1par, albd, xlai, rsd, rsmin, rsmax, Rpl, tkel, vppa, f3vpd, f3vpdpar, f4temp, trefk, f4temppar, rnetpn, gbspen, rnetd, rnetw, gd, gw, rescan, ravd, xlhv, row, epetd, epetw, ravw, psychr, xled, xlew, hd, hw, cp, roa)
subroutine peteb (ipix, i, dt, inc_frozen,
real *8 function esat (Tsk)
function clcf1par (alb, LAI, Rg, rsmin, rsmax, Rgl)
function clcf3vpd (Ts, ea, g)
function clcf4temp (tair, tref, f4par)
subroutine peteb_bs (thermc1, thermc2, heatcap1, heatcap2, heatcapold, rain, snow, Swq, albd, emiss, ravd, rahd, tkd, tkmidd, rnetd, xled, epetd, hd, gd, dshd, tcel, vppa, roa, psychr, xlhv, zdeep, Tdeepstep, zmid, rsd, rld, toleb, maxnri, dt, i, tkw, tkmidw, rnetw, xlew, epetw, hw, gw, dshw, ravw, rahw, PackWater, SurfWater, VaporMassFlux, TPack, TSurf, r_MeltEnergy, Outflow, xleact_snow, hact_snow, rn_snow, dens, za, zpd, albw, z0h, RaSnow, alb_snow, appa, vpsat, uzw, gact, row)
subroutine peteb_dv (thermc2, vpsat, heatcap, heatcap2, heatcapold, rs_over, rain, snow, Swq, albd, emiss, thermc, f1par, f3vpd, f4temp, rescan, ravd, rahd, tkd, tkmidd, rnetd, xled, epetd, hd, gd, dshd, tcel, vppa, roa, psychr, xlhv, zdeep, Tdeepstep, zmid, rld, toleb, maxnri, dt, i, PackWater, SurfWater, VaporMassFlux, TPack, TSurf, r_MeltEnergy, Outflow, xleact_snow, hact_snow, rn_snow, dens, za, zpd, z0h, RaSnow, appa, uzw, gact, alb_snow, row)
subroutine peteb_wv (thermc2, heatcap, heatcap2, heatcapold, rs_over, rain, snow, Swq, albw, emiss, thermc, ravw, rahw, tkw, tkmidw, rnetw, xlew, epetw, hw, gw, dshw, tcel, vppa, roa, psychr, xlhv, zdeep, Tdeepstep, zmid, rld, toleb, maxnri, dt, i, iopstab, tkact, zww, za, uzw, zpd, z0m, tkel, press, rib, z0h, PackWater, SurfWater, VaporMassFlux, TPack, TSurf, r_MeltEnergy, Outflow, xleact_snow, hact_snow, rn_snow, dens, RaSnow, alb_snow, appa, vpsat, gact, row, ipix)
subroutine inidum (dum1, PackWater, dum2, SurfWater, dum3, Swq, dum4, VaporMassFlux, dum5, TPack, dum6, TSurf, dum7, r_MeltEnergy, dum8, Outflow, dum9, xleact_snow, dum10, hact_snow, dum11, rn_snow, dum12, dens)
Detailed Description
Definition at line 1 of file MODULE_ATMOS.f90.
Member Function/Subroutine Documentation
subroutine module_atmos::atmos (ipix, i, dt, inc_frozen, i_2l)
Definition at line 34 of file MODULE_ATMOS.f90.
References appa, bcbeta, module_shared::calcra(), cp, cph2o, d0, dens, dens_us, ds_p_moss, dshact, dshact_moss, dshact_us, dshd, dshd_us, dshw, dshw_us, dspet, dspet_moss, dspet_us, dt, eact_moss, ebspot, emiss, emiss_moss, emiss_us, epet_moss, epetd, epetd_us, epetw, epetw_us, eps, f1, f1par, f1par_us, f2, f3, f3vpd, f3vpd_us, f3vpdpar, f3vpdpar_us, f4temp, f4temp_us, f4temppar, f4temppar_us, g_p_moss, gact, gbspen, gd, gd_us, gw, gw_us, h_p_moss, hact_snow, hact_snow_us, hd, hd_us, hw, hw_us, i, ifcoarse, inc_frozen, inittk(), iopgveg, ioppet, iopsmini, iopstab, iopthermc, iopthermc_v, iopwv, ipix, maxnri, one, peteb(), petpen(), psic, psychr, psychr_ic, quartz, qv, qv_ic, r_moss_depth, r_mossm, ra, ra_ic, rah_moss, rahd, rahd_us, rahw, rahw_us, rasnow, rav_moss, ravd, ravd_us, ravw, ravw_us, rescan, rescan_us, rib, rib_moss, rib_us, rn_snow, rn_snow_us, rnet_pot_moss, rnetd, rnetd_us, rnetpn, rnetw, rnetw_us, roa, roa_ic, rocpsoil, roi, row, rrr, rrrr, rsmax, rsmax_us, rsmin, rsmin_us, rzdthetaudtemp, rzsm, rzsm1, smold, smpet0, module_shared::stabcor(), tcbeta, tcbeta_us, tcel, tcel_ic, thetar, thetas, tk_p_moss, tkact_moss, tkact_us, tkactd_moss, tkd, tkd_us, tkel, tkel_ic, tkmid, tkmid_moss, tkmid_p_moss, tkmid_us, tkmidactd_moss, tkmidd, tkmidd_us, tkmidpet, tkmidpet_moss, tkmidpet_us, tkmidw, tkmidw_us, tkpet, tkw, tkw_us, toleb, trefk, trefk_us, tskin_p_moss, tskinact_moss, tskinactd_moss, tsoilold, tsurf, twet, tzsm, tzsm1, uzw, vpdef, vppa, vppa_ic, vpsat, vpsat_ic, xlai, xlai_us, xle_act_moss, xle_p_moss, xleact_snow, xleact_snow_us, xled, xled_us, xlew, xlew_us, xlhv, xlhv_ic, z0h, z0h_moss, z0h_us, z0m, z0m_moss, z0m_us, zdeep, zero, zmid, zpd, zpd_moss, zpd_us, zrz, and zrzmax.
Referenced by module_cell::update_cell().
function module_atmos::clcf1par (alb, LAI, Rg, rsmin, rsmax, Rgl)
Definition at line 1640 of file MODULE_ATMOS.f90.
References a1, a2, alb, clcf1par, d0, f, f1par, par, rsmax, and rsmin.
function module_atmos::clcf3vpd (Ts, ea, g)
Definition at line 1679 of file MODULE_ATMOS.f90.
References clcf3vpd, d0, ea, esat(), f3vpd, g, rmax_vpd, rmin_vpd, ts, and vpd.
function module_atmos::clcf4temp (tair, tref, f4par)
Definition at line 1733 of file MODULE_ATMOS.f90.
References d0, f4par, f4temp, rmax_tair, rmin_tair, tair, and tref.
Referenced by module_unit_tests::clcf4temp_test1(), module_unit_tests::clcf4temp_test2(), peteb(), and petpen().
real*8 function module_atmos::esat (real*8 Tsk)
Definition at line 1595 of file MODULE_ATMOS.f90.
References d0.
Referenced by clcf3vpd(), module_unit_tests::esat_test1(), and module_unit_tests::esat_test2().
subroutine module_atmos::inidum (dum1, PackWater, dum2, SurfWater, dum3, Swq, dum4, VaporMassFlux, dum5, TPack, dum6, TSurf, dum7, r_MeltEnergy, dum8, Outflow, dum9, xleact_snow, dum10, hact_snow, dum11, rn_snow, dum12, dens)
Definition at line 2119 of file MODULE_ATMOS.f90.
References dens, dum1, dum10, dum11, dum12, dum2, dum3, dum4, dum5, dum6, dum7, dum8, dum9, hact_snow, rn_snow, swq(), tsurf, and xleact_snow.
Referenced by peteb_bs(), peteb_dv(), and peteb_wv().
subroutine module_atmos::inittk (type (grid_soil_template) GRID_SOIL, type (grid_veg_template) GRID_VEG, type (grid_vars_template) GRID_VARS, tdeep, tmid0, tmid0_moss, tkmid, tkmid_us, tkmid_moss, tkel, tk0moss, tkact, tkact_us, tkact_moss, tskinact_moss, dshact, dshact_us, dshact_moss, tkpet, tkmidpet, tkmidpet_us, tkmidpet_moss, dspet, dspet_us, dspet_moss, Tsurf, Tpack, Tsurf_us, Tpack_us)
Definition at line 766 of file MODULE_ATMOS.f90.
References d0, dshact, dshact_moss, dshact_us, dspet, dspet_moss, dspet_us, tdeep, tk0moss, tkact, tkact_moss, tkact_us, tkel, tkmid, tkmid_moss, tkmid_us, tkmidpet, tkmidpet_moss, tkmidpet_us, tkmidtmp, tkmidtmp_us, tkpet, tmid0, tmid0_moss, tskinact_moss, tsurf, ttemp, and zero.
Referenced by atmos().
subroutine module_atmos::peteb (ipix, i, dt, inc_frozen)
Definition at line 1050 of file MODULE_ATMOS.f90.
References alb_moss, alb_snow, albd, albd_us, albw, albw_us, appa, bcbeta, module_shared::calc_rs(), clcf1par, clcf3vpd, clcf4temp(), cp, cph2o, d0, dens, dens_us, ds_p_moss, dshact, dshact_moss, dshact_us, dshd, dshd_us, dshw, dshw_us, dt, eact_moss, emiss, emiss_moss, emiss_us, epet_moss, epetd, epetd_us, epetw, epetw_us, eps, f1, f1par, f1par_us, f2, f3, f3vpd, f3vpd_us, f3vpdpar, f3vpdpar_us, f4temp, f4temp_us, f4temppar, f4temppar_us, g_p_moss, gact, gd, gd_us, gw, gw_us, h_p_moss, hact_snow, hact_snow_us, hd, hd_us, heatcap, heatcap1, heatcap2, heatcap_us, heatcapold, hw, hw_us, i, i_moss, i_und, ifcoarse, iffroz, inc_frozen, iopgveg, iopsmini, iopstab, iopthermc, iopthermc_v, ipix, ivgtyp, maxnri, peteb_bs(), peteb_dv(), peteb_wv(), press, psic, psychr, psychr_ic, quartz, r_moss_depth, r_mossm, rah_moss, rahd, rahd_us, rahw, rahw_us, rain, rasnow, rav_moss, ravd, ravd_us, ravw, ravw_us, rescan, rescan_us, rib, rib_moss, rib_us, rld, rn_snow, rn_snow_us, rnet_pot_moss, rnetd, rnetd_us, rnetw, rnetw_us, roa, roa_ic, rocpsoil, roi, row, rs_over, rs_under, rsd, rsmax, rsmax_us, rsmin, rsmin_us, rzdthetaudtemp, rzsm, rzsm1, module_shared::sm_cen_dif(), smold, smpet0, smtmp, snow, module_shared::soiladapt(), module_shared::soiltherm(), swq(), tcbeta, tcbeta_us, tcel, tcel_ic, thermc, thermc1, thermc2, thermc_us, thetar, thetas, tk_p_moss, tkact, tkact_moss, tkact_us, tkactd_moss, tkd, tkd_us, tkel, tkel_ic, tkmid, tkmid_moss, tkmid_p_moss, tkmid_us, tkmidactd_moss, tkmidd, tkmidd_us, tkmidw, tkmidw_us, tkw, tkw_us, toleb, trefk, trefk_us, tskin_p_moss, tskinact_moss, tskinactd_moss, tsurf, tzsm, tzsm1, uzw, vppa, vppa_ic, vpsat, vpsat_ic, xlai, xlai_us, xle_act_moss, xle_p_moss, xleact_snow, xleact_snow_us, xled, xled_us, xlew, xlew_us, xlhv, xlhv_ic, z0h, z0h_moss, z0h_us, z0m, z0m_moss, z0m_us, za, zdeep, zero, zmid, zpd, zpd_moss, zpd_us, zrz, zrzmax, and zww.
Referenced by atmos().
subroutine module_atmos::peteb_bs (thermc1, thermc2, heatcap1, heatcap2, heatcapold, rain, snow, Swq, albd, emiss, ravd, rahd, tkd, tkmidd, rnetd, xled, epetd, hd, gd, dshd, tcel, vppa, roa, psychr, xlhv, zdeep, Tdeepstep, zmid, rsd, rld, toleb, maxnri, dt, i, tkw, tkmidw, rnetw, xlew, epetw, hw, gw, dshw, ravw, rahw, PackWater, SurfWater, VaporMassFlux, TPack, TSurf, r_MeltEnergy, Outflow, xleact_snow, hact_snow, rn_snow, dens, za, zpd, albw, z0h, RaSnow, alb_snow, appa, vpsat, uzw, gact, row)
Definition at line 1785 of file MODULE_ATMOS.f90.
References alb_snow, albd, albw, appa, module_snow::calcsnowmelt(), d0, dens, dshd, dshw, dt, dum, dum1, dum10, dum11, dum12, dum2, dum3, dum4, dum5, dum6, dum7, dum8, dum9, emiss, epetd, epetw, gact, gd, gw, hact_snow, hd, heatcap1, heatcap2, heatcapold, hw, i, inidum(), maxnri, module_shared::nreb(), module_shared::nreb_snow(), psychr, rahd, rahw, rain, rasnow, ravd, ravw, rld, rn_snow, rnetd, rnetw, roa, row, rsd, snow, swq(), tcel, thermc1, thermc2, tkd, tkmidd, tkmidw, tkw, toleb, tsnow, tsurf, uzw, vppa, vpsat, xleact_snow, xled, xlew, xlhv, z0h, za, zdeep, zmid, and zpd.
Referenced by peteb().
subroutine module_atmos::peteb_dv (thermc2, vpsat, heatcap, heatcap2, heatcapold, rs_over, rain, snow, Swq, albd, emiss, thermc, f1par, f3vpd, f4temp, rescan, ravd, rahd, tkd, tkmidd, rnetd, xled, epetd, hd, gd, dshd, tcel, vppa, roa, psychr, xlhv, zdeep, Tdeepstep, zmid, rld, toleb, maxnri, dt, i, PackWater, SurfWater, VaporMassFlux, TPack, TSurf, r_MeltEnergy, Outflow, xleact_snow, hact_snow, rn_snow, dens, za, zpd, z0h, RaSnow, appa, uzw, gact, alb_snow, row)
Definition at line 1897 of file MODULE_ATMOS.f90.
References alb_snow, albd, appa, module_snow::calcsnowmelt(), d0, dens, dshd, dt, dum, dum1, dum10, dum11, dum12, dum2, dum3, dum4, dum5, dum6, dum7, dum8, dum9, emiss, epetd, f1par, f3vpd, f4temp, gact, gd, hact_snow, hd, heatcap, heatcap2, heatcapold, i, inidum(), maxnri, module_shared::nreb(), module_shared::nreb_snow(), psychr, rahd, rain, rasnow, ravd, rescan, rld, rn_snow, rnetd, roa, row, rs_over, snow, swq(), tcel, thermc, thermc2, tkd, tkmidd, toleb, tsnow, tsurf, uzw, vppa, vpsat, xleact_snow, xled, xlhv, z0h, za, zdeep, zmid, and zpd.
Referenced by peteb().
subroutine module_atmos::peteb_wv (thermc2, heatcap, heatcap2, heatcapold, rs_over, rain, snow, Swq, albw, emiss, thermc, ravw, rahw, tkw, tkmidw, rnetw, xlew, epetw, hw, gw, dshw, tcel, vppa, roa, psychr, xlhv, zdeep, Tdeepstep, zmid, rld, toleb, maxnri, dt, i, iopstab, tkact, zww, za, uzw, zpd, z0m, tkel, press, rib, z0h, PackWater, SurfWater, VaporMassFlux, TPack, TSurf, r_MeltEnergy, Outflow, xleact_snow, hact_snow, rn_snow, dens, RaSnow, alb_snow, appa, vpsat, gact, row, integer ipix)
Definition at line 1998 of file MODULE_ATMOS.f90.
References alb_snow, albw, appa, module_shared::calcra(), module_snow::calcsnowmelt(), d0, dens, dshw, dt, dum, dum1, dum10, dum11, dum12, dum2, dum3, dum4, dum5, dum6, dum7, dum8, dum9, emiss, epetw, gact, gw, hact_snow, heatcap, heatcap2, heatcapold, hw, i, inidum(), iopstab, ipix, iter, maxnri, module_shared::nreb(), module_shared::nreb_snow(), press, psychr, rahw, rain, rasnow, ravw, rib, rld, rn_snow, rnetw, roa, row, rs_over, snow, module_shared::stabcor(), swq(), tcel, thermc, thermc2, tkact, tkel, tkmidw, tktmp, tkw, toleb, tsnow, tsurf, uzw, vppa, vpsat, xleact_snow, xlew, xlhv, z0h, z0m, za, zdeep, zmid, zpd, and zww.
Referenced by peteb().
subroutine module_atmos::petpen (type (grid_veg_template) GRID_VEG, type (grid_met_template) GRID_MET, type (grid_vars_template) GRID_VARS, tcel, vpsat, vpdef, f1par, albd, xlai, rsd, rsmin, rsmax, Rpl, tkel, vppa, f3vpd, f3vpdpar, f4temp, trefk, f4temppar, rnetpn, gbspen, rnetd, rnetw, gd, gw, rescan, ravd, xlhv, row, epetd, epetw, ravw, psychr, xled, xlew, hd, hw, cp, roa)
Definition at line 890 of file MODULE_ATMOS.f90.
References albd, clcf3vpd, clcf4temp(), cp, d0, dvpsdt, epetd, epetdmf, epetw, epetwmf, f1par, f3vpd, f3vpdpar, f4temp, f4temppar, gbspen, gd, gw, hd, hw, one, pstar, psychr, ravd, ravw, rescan, rnetd, rnetpn, rnetw, roa, row, rsd, rsmax, rsmin, tcel, tkel, trefk, two, vpdef, vppa, vpsat, xlai, xled, xlew, and xlhv.
Referenced by atmos().
The documentation for this module was generated from the following file:
MODEL/MODULE_ATMOS.f90