module_topmodel Module Reference
module_topmodel Module Reference
Public Member Functions
subroutine update_catchments (GLOBAL, CAT, GRID)
run TOPMODEL in specified catchments
subroutine instep_catchment (ncatch, CAT)
Initialize regional scale water balance variables.
subroutine catflx (pixsiz, CAT)
Calculates the catchment time step totals of evapotranspiration, runoff, surface energy fluxes and vertical soil-water fluxes.
subroutine upzbar (ic, CAT, GLOBAL, GRID)
Updates the average water table depth.
subroutine sumflx_catchment (CAT, GRID_VARS, GLOBAL, GRID_VEG, GRID_SOIL, GRID_MET, ilandc)
Calculates the time step totals of evapotranspiration, runoff, surface energy fluxes and vertical soil-water fluxes.
Detailed Description
Definition at line 1 of file MODULE_TOPMODEL.f90.
Member Function/Subroutine Documentation
subroutine module_topmodel::catflx (real*8 pixsiz, type (catchment_template), intent(inout) CAT)
Calculates the catchment time step totals of evapotranspiration, runoff, surface energy fluxes and vertical soil-water fluxes.
Definition at line 142 of file MODULE_TOPMODEL.f90.
References capsum, f10, fwcat, gwtsum, one, pixsiz, rzpsum, and tzpsum.
Referenced by update_catchments().
subroutine module_topmodel::instep_catchment (integer, intent(in) ncatch, type (catchment_template), dimension(:), intent(inout) CAT)
Initialize regional scale water balance variables.
Definition at line 62 of file MODULE_TOPMODEL.f90.
References kk, ncatch, and zero.
Referenced by toplats_driver().
subroutine module_topmodel::sumflx_catchment (type (catchment_template), intent(inout) CAT, type (grid_vars_template), intent(in) GRID_VARS, type (global_template), intent(in) GLOBAL, type (grid_veg_template), intent(in) GRID_VEG, type (grid_soil_template), intent(in) GRID_SOIL, type (grid_met_template), intent(in) GRID_MET, integer ilandc)
Calculates the time step totals of evapotranspiration, runoff, surface energy fluxes and vertical soil-water fluxes.
Definition at line 490 of file MODULE_TOPMODEL.f90.
References bsdew, canclos, capsum, d0, dc, dc_us, difrz, diftz, dshact, dspet, dsrz, dstz, dswc, dt, dummy, epwms, epwms_us, etpix(), evtact, evtact_moss, evtact_us, f11, f_moss, f_und, fw, fw_us, gact, gpet, grz, gtz, gwtsum, hact, hpet, i_und, ilandc, inc_frozen, ivgtyp, one, pnet, pptms, rnact, rnpet, runtot, rzpsum, rzrhs, rzsm, rzsm1, rzsm1_u, satxr, swq(), tair, thetas, tkact, tkmid, tkmidpet, tkpet, tskinact_moss, tzpsum, tzrhs, tzsm, tzsm1, tzsm1_u, wcip1, xinfxr, xleact, xleact_moss, xleact_us, xlepet(), xlhv, zero, zrz, and ztz.
Referenced by update_catchments().
subroutine module_topmodel::update_catchments (type (global_template), intent(in) GLOBAL, type (catchment_template), dimension(:), intent(inout) CAT, type (grid_template), dimension(:), intent(inout) GRID)
run TOPMODEL in specified catchments
Definition at line 21 of file MODULE_TOPMODEL.f90.
References catflx(), icatch(), ilandc, ipix, isoil(), sumflx_catchment(), and upzbar().
Referenced by toplats_driver().
subroutine module_topmodel::upzbar (integer ic, type (catchment_template), intent(inout) CAT, type (global_template), intent(in) GLOBAL, type (grid_template), dimension(:), intent(inout) GRID)
Updates the average water table depth.
Definition at line 301 of file MODULE_TOPMODEL.f90.
References basink, capsum, d0, dd, dt, dtil(), ff, gwtsum, hbar, ic, icatch(), ilandc, iopbf, isoil(), ivgtyp, npix, pixsiz, psic, q0, qb, qbreg, qzbar, rzpsum, rzsm1, thetas, tzpsum, tzsm1, zbar, zbar1, zbrflx, zbrpor, zero, zrzmax, and zw.
Referenced by update_catchments().
The documentation for this module was generated from the following file:
MODEL/MODULE_TOPMODEL.f90