module_snow Module Reference
module_snow Module Reference
Public Member Functions
subroutine calcsnowmelt (y, x, Tstep, Z, Displacement, Z0, BaseRa, AirDens, EactAir, Lv, ShortRad, LongRadIn, Press, RainFall, SnowFall, Tair, Vpd, Wind, PackWater, SurfWater, Swq, VaporMassFlux, TPack, TSurf, MeltEnergy, Outflow, LatentHeat, SensibleHeat, NetRad, Emiss, Density, Gact)
Calculate snow accumulation and melt using an energy balance approach for a two layer snow model.
subroutine rootbrent (y, x, LowerBound, UpperBound, aaa, Tstep, BaseRa, Z, Displacement, Z0, Wind, ShortRad, LongRadIn, AirDens, Lv, Tair, Press, Vpd, EactAir, RainFall, SurfaceSwq, SurfWater, OldTSurf, RefreezeEnergy, VaporMassFlux, b, LatentHeat, SensibleHeat, NetRad, Emiss, Gact, R_MAX_SURFACE_SWE, Swq)
Calculate the surface temperature in the absence of snow.
subroutine snowpackenergybalance (TSurf, Tstep, Ra, Z, Displacement, Z0, Wind, ShortRad, LongRadIn, AirDens, Lv, Tair, Press, Vpd, EactAir, Rain, SweSurfaceLayer, SurfaceLiquidWater, OldTSurf, RefreezeEnergy, VaporMassFlux, RestTerm, LatentHeat, SensibleHeat, NetRad, Emiss, Gact, R_MAX_SURFACE_SWE, Swq)
Calculate the surface energy balance for the snow pack.
function stabilitycorrection (Z, d, TSurf, Tair, Wind, Z0)
Calculate atmospheri! stability correction for non-neutral conditions.
subroutine satvaporpressure (tair, satvap)
subroutine snow_density (dens, snow_m, tcel, Swq_m, snow_depth, Tsurf, tstep)
Calculate the density of the snow pack.
Detailed Description
Definition at line 1 of file MODULE_SNOW.f90.
Member Function/Subroutine Documentation
subroutine module_snow::calcsnowmelt (integer y, integer x, real*8 Tstep, real*8 Z, real*8 Displacement, real*8 Z0, real*8 BaseRa, real*8 AirDens, real*8 EactAir, real*8 Lv, real*8 ShortRad, real*8 LongRadIn, real*8 Press, real*8 RainFall, real*8 SnowFall, real*8 Tair, real*8 Vpd, real*8 Wind, real*8 PackWater, real*8 SurfWater, real*8 Swq, real*8 VaporMassFlux, real*8 TPack, real*8 TSurf, real*8 MeltEnergy, real*8 Outflow, real*8 LatentHeat, real*8 SensibleHeat, real*8 NetRad, real*8 Emiss, real*8 Density, real*8 Gact)
Calculate snow accumulation and melt using an energy balance approach for a two layer snow model.
Definition at line 86 of file MODULE_SNOW.f90.
References cp, d(), d0, d3, emiss, eps, g, gact, p1, p2, parameter(), press, rainfall(), rootbrent(), snowpackenergybalance(), swq(), tair, tsurf, vpd, x, y(), z, and zero.
Referenced by module_land::land(), module_land::land_os(), module_land::land_us(), module_atmos::peteb_bs(), module_atmos::peteb_dv(), and module_atmos::peteb_wv().
subroutine module_snow::rootbrent (integer y, integer x, real*8 LowerBound, real*8 UpperBound, real*8 aaa, real*8 Tstep, real*8 BaseRa, real*8 Z, real*8 Displacement, real*8 Z0, real*8 Wind, real*8 ShortRad, real*8 LongRadIn, real*8 AirDens, real*8 Lv, real*8 Tair, real*8 Press, real*8 Vpd, real*8 EactAir, real*8 RainFall, real*8 SurfaceSwq, real*8 SurfWater, real*8 OldTSurf, real*8 RefreezeEnergy, real*8 VaporMassFlux, real*8 b, real*8 LatentHeat, real*8 SensibleHeat, real*8 NetRad, real*8 Emiss, real*8 Gact, R_MAX_SURFACE_SWE, real*8 Swq)
Calculate the surface temperature in the absence of snow.
Definition at line 763 of file MODULE_SNOW.f90.
References a, b, c, d(), d0, emiss, gact, i, j, m, maxiter, p, parameter(), press, rainfall(), s, snowpackenergybalance(), swq(), t, tair, vpd, z, and zero.
Referenced by calcsnowmelt().
subroutine module_snow::satvaporpressure (real*8 tair, real*8 satvap)
Definition at line 1388 of file MODULE_SNOW.f90.
References d0, tair, and zero.
Referenced by snowpackenergybalance().
subroutine module_snow::snow_density (real*8 dens, real*8 snow_m, real*8 tcel, real*8 Swq_m, real*8 snow_depth, real*8 Tsurf, real*8 tstep)
Calculate the density of the snow pack.
Definition at line 1446 of file MODULE_SNOW.f90.
References d0, dens, dt, g, parameter(), tcel, and tsurf.
Referenced by module_cell::update_cell().
subroutine module_snow::snowpackenergybalance (real*8 TSurf, real*8 Tstep, real*8 Ra, real*8 Z, real*8 Displacement, real*8 Z0, real*8 Wind, real*8 ShortRad, real*8 LongRadIn, real*8 AirDens, real*8 Lv, real*8 Tair, real*8 Press, real*8 Vpd, real*8 EactAir, real*8 Rain, real*8 SweSurfaceLayer, real*8 SurfaceLiquidWater, real*8 OldTSurf, real*8 RefreezeEnergy, real*8 VaporMassFlux, real*8 RestTerm, real*8 LatentHeat, real*8 SensibleHeat, real*8 NetRad, real*8 Emiss, real*8 Gact, R_MAX_SURFACE_SWE, real*8 Swq)
Calculate the surface energy balance for the snow pack.
Definition at line 1088 of file MODULE_SNOW.f90.
References cp, d(), d0, d3, emiss, eps, gact, parameter(), press, ra, rain, satvaporpressure(), stabilitycorrection(), swq(), tair, tsurf, vpd, and zero.
Referenced by calcsnowmelt(), and rootbrent().
function module_snow::stabilitycorrection (real*8 Z, real*8 d, real*8 TSurf, real*8 Tair, real*8 Wind, real*8 Z0)
Calculate atmospheri! stability correction for non-neutral conditions.
Definition at line 1324 of file MODULE_SNOW.f90.
References d(), d0, g, parameter(), tair, tsurf, z, and zero.
Referenced by snowpackenergybalance().
The documentation for this module was generated from the following file:
MODEL/MODULE_SNOW.f90