module_cell Module Reference
module_cell Module Reference
Public Member Functions
subroutine update_cells (GRID, CAT, GLOBAL, i)
subroutine update_cell (ipix, i, GRID_MET, GRID_SOIL, GRID_VEG, GRID_VARS, wcip1, CAT, GLOBAL)
Detailed Description
Definition at line 1 of file MODULE_CELL.f90.
Member Function/Subroutine Documentation
subroutine module_cell::update_cell (ipix, i, type (grid_met_template) GRID_MET, type (grid_soil_template) GRID_SOIL, type (grid_veg_template) GRID_VEG, type (grid_vars_template) GRID_VARS, wcip1, type (catchment_template) CAT, type (global_template) GLOBAL)
Definition at line 72 of file MODULE_CELL.f90.
References a_ice, a_ice_moss, alb_moss, alb_snow, albd, albd_us, albw, amp, appa, atanb, module_atmos::atmos(), b_ice, b_ice_moss, bcbeta, bcgamm, bsdew, bsdew_moss, bulk_dens, bulk_dens_moss, module_land::calcrain(), canclos, module_canopy::canopy(), capflx, cc, corr, cp, cph2o, cuminf, d0, dc, dc_us, deltrz, dens, dens_us, dewrun, difrz, diftz, ds_p_moss, dshact, dshact_moss, dshact_us, dshd, dshd_us, dshw, dshw_us, dspet, dspet_moss, dspet_us, dsrz, dsty, dsty_us, dstz, dswc, dt, eact_moss, ebspot, emiss, emiss_moss, emiss_us, endstm, epet_moss, epetd, epetd_us, epetw, epetw_us, eps, epwms, evtact, evtact_moss, evtact_us, extinct, f1, f1par, f1par_us, f2, f3, f3vpd, f3vpd_us, f3vpdpar, f3vpdpar_us, f4temp, f4temp_us, f4temppar, f4temppar_us, f_moss, f_und, ff, fw, fw_us, fwcat, fwreg, g_p_moss, gact, gact_moss, gact_us, gbspen, gd, gd_us, gpet, grz, gtz, gw, gw_us, h_p_moss, hact, hact_moss, hact_snow, hact_snow_us, hact_us, hd, hd_us, hpet, hw, hw_us, i, i_2l, i_moss, i_und, idifind, ievcon, ievcon_moss, ievcon_us, ifcoarse, ikopt, inc_frozen, intstm, intstm_moss, intstp, iopgveg, ioppet, iopsmini, iopstab, iopthermc, iopthermc_v, iopveg, iopwv, ipix, irestype, irntyp, istmst, istmst_moss, istorm, ivgtyp, module_land::land(), maxnri, newstorm, par, perixr, perrg1, perrg2, persac, persxr, peruac, phase, pnet, pptms, pr1rzs, pr1sat, pr1tzs, pr1uns, pr2sat, pr2uns, pr3sat, precip_o, precip_u, press, psic, psicri, psychr, psychr_ic, quartz, qv, qv_ic, r_moss_depth, r_mossm, r_mossm1, r_mossm1_f, r_mossm1_u, r_mossm_f, r_mossm_u, r_mossmold, ra, ra_ic, rah_moss, rahd, rahd_us, rahw, rahw_us, rain, rasnow, rav_moss, ravd, ravd_us, ravw, ravw_us, rescan, rescan_us, respla, rh, rh_ic, rib, rib_moss, rib_us, rld, rn_snow, rn_snow_us, rnact, rnact_moss, rnact_us, rnet_pot_moss, rnetd, rnetd_us, rnetpn, rnetw, rnetw_us, rnpet, roa, roa_ic, rocpsoil, roi, row, rrr, rsd, rsmax, rsmax_us, rsmin, rsmin_us, rtact, rtdens, runtot, rzdthetaidt, rzdthetaudtemp, rzrhs, rzsm, rzsm1, rzsm1_f, rzsm1_u, rzsm_f, rzsm_u, rzsmold, satxr, sesq, shift, smold, smpet0, snow, module_snow::snow_density(), sorp, srespar1, srespar1_moss, srespar2, srespar2_moss, srespar3, srespar3_moss, swq(), tc, tc_us, tcbeta, tcbeta_us, tcel, tcel_ic, tdeep, tdry, thetar, thetas, thetas_moss, tk_p_moss, tkact, tkact_moss, tkact_us, tkactd_moss, tkd, tkd_us, tkel, tkel_ic, tkmid, tkmid_moss, tkmid_p_moss, tkmid_us, tkmidactd_moss, tkmidd, tkmidd_us, tkmidpet, tkmidpet_moss, tkmidpet_us, tkmidw, tkmidw_us, tkpet, tkw, tkw_us, tmid0, toleb, trefk, trefk_us, tskin_p_moss, tskinact_moss, tskinactd_moss, tsoilold, tsurf, tw, tw_us, twet, tzdthetaidt, tzrhs, tzsm, tzsm1, tzsm1_f, tzsm1_u, tzsm_f, tzsm_u, tzsmold, uzw, vppa, vppa_ic, vpsat, vpsat_ic, wcip1, wsc, xinact, xinfxr, xk0, xlai, xlai_us, xlamda, xle_act_moss, xle_p_moss, xleact, xleact_moss, xleact_snow, xleact_snow_us, xleact_us, xled, xled_us, xlepet(), xlew, xlew_us, xlhv, xlhv_ic, z0h, z0h_moss, z0h_us, z0m, z0m_moss, z0m_us, za, zbar, zdeep, zmid, zmoss, zpd, zpd_moss, zpd_us, zrz, zrzmax, ztz, zw, and zww.
Referenced by update_cells().
subroutine module_cell::update_cells (type (grid_template), dimension(:), intent(inout) GRID, type (catchment_template), dimension(:), intent(inout) CAT, type (global_template), intent(in) GLOBAL, integer, intent(in) i)
Definition at line 25 of file MODULE_CELL.f90.
References i, icatch(), ilandc, ipix, isoil(), and update_cell().
Referenced by toplats_driver().
The documentation for this module was generated from the following file:
MODEL/MODULE_CELL.f90