MODEL/help/imgctl.h File Reference
imgctl.h File Reference
Functions
real * tkact (MAX_PIX)
real gact (MAX_PIX)
real hact (MAX_PIX) real *8 xleact(MAX_PIX)
real rnact (MAX_PIX)
real etpix (MAX_PIX) real *8 runtot(MAX_PIX)
real xinact (MAX_PIX) real *8 zw(MAX_PIX)
real tzsm1 (MAX_PIX)
real rzsm1 (MAX_PIX) real *8 tkpet(MAX_PIX)
real wcip1 (MAX_PIX)
real gpet (MAX_PIX) real *8 hpet(MAX_PIX)
real xlepet (MAX_PIX)
real rnpet (MAX_PIX) real *8 r_mossm(1+MOS_FLG *(MAX_PIX-1))
real pptms (MAX_PIX)
real pptsumrg real * Swq (1+SNOW_RUN *(MAX_PIX-1)) real *8 Swq_us(1+SNW_FLG *(MAX_PIX-1)) integer ievcon(MAX_PIX)
real pptsumrg real ipixnum (MAX_ROW, MAX_COL)
real pptsumrg real nrow integer icurser (MAX_FIL)
real pptsumrg real nrow integer nseries (MAX_FIL)
real pptsumrg real nrow integer iouten (MAX_FIL, MAX_SER) integer ioutst(MAX_FIL
real pptsumrg real nrow integer iprn (MAX_FIL)
real pptsumrg real nrow
integer i integer ioutsp (MAX_FIL, MAX_SER)
real pptsumrg real nrow
integer i integer irntyp (MAX_PIX) integer img_opt
real pptsumrg real nrow
integer i integer ihour
character * fnimg (MAX_FIL) integer imgprn(MAX_FIL)
Variables
real pptsumrg real ncol
real pptsumrg real nrow integer MAX_SER
real pptsumrg real nrow
integer i integer iyear
real pptsumrg real nrow
integer i integer iday
Function Documentation
real etpix (MAX_PIX)
Referenced by module_topmodel::sumflx_catchment(), and module_regional::sumflx_regional().
real pptsumrg real nrow integer i integer ihour character* fnimg (MAX_FIL)
real gact (MAX_PIX)
real gpet (MAX_PIX)
real hact (MAX_PIX)
real pptsumrg real nrow integer icurser (MAX_FIL)
real pptsumrg real nrow integer iouten (MAX_FIL , MAX_SER)
real pptsumrg real nrow integer i integer ioutsp (MAX_FIL , MAX_SER)
real pptsumrg real ipixnum (MAX_ROW , MAX_COL)
real pptsumrg real nrow integer iprn (MAX_FIL)
real pptsumrg real nrow integer i integer irntyp (MAX_PIX)
real pptsumrg real nrow integer nseries (MAX_FIL)
real pptms (MAX_PIX)
real rnact (MAX_PIX)
real rnpet (MAX_PIX)
real rzsm1 (MAX_PIX)
real pptsumrg real* Swq (1+SNOW_RUN * MAX_PIX-1)
real* tkact (MAX_PIX)
real tzsm1 (MAX_PIX)
real wcip1 (MAX_PIX)
real xinact (MAX_PIX)
real xlepet (MAX_PIX)
Referenced by module_topmodel::sumflx_catchment(), module_regional::sumflx_regional(), and module_cell::update_cell().
Variable Documentation
real pptsumrg real nrow integer i integer iday
Definition at line 15 of file imgctl.h.
real pptsumrg real nrow integer i integer iyear
Definition at line 15 of file imgctl.h.
real pptsumrg real nrow integer MAX_SER
Definition at line 13 of file imgctl.h.
real pptsumrg real ncol
Definition at line 11 of file imgctl.h.