TOPLATS: fruit_util::to_s Interface Reference
fruit_util::to_s Interface Reference
Private Member Functions
character(len=500) function to_s_int_ (value)
character(len=500) function to_s_real_ (value)
character(len=500) function to_s_logical_ (value)
character(len=500) function to_s_double_ (value)
character(len=500) function to_s_complex_ (value)
character(len=500) function to_s_double_complex_ (value)
character(len=500) function to_s_string_ (value)
Detailed Description
Definition at line 15 of file fruit_util.f90.
Member Function/Subroutine Documentation
character(len=500) function fruit_util::to_s::to_s_complex_ (complex, intent(in) value) private
Definition at line 58 of file fruit_util.f90.
Referenced by fruit_util::to_s_complex_().
character(len=500) function fruit_util::to_s::to_s_double_ (double precision, intent(in) value) private
Definition at line 49 of file fruit_util.f90.
Referenced by fruit_util::to_s_double_().
character(len=500) function fruit_util::to_s::to_s_double_complex_ (complex(kind=kind(1.0d0)), intent(in) value) private
Definition at line 67 of file fruit_util.f90.
Referenced by fruit_util::to_s_double_complex_().
character(len=500) function fruit_util::to_s::to_s_int_ (integer, intent(in) value) private
Definition at line 31 of file fruit_util.f90.
Referenced by fruit_util::to_s_int_().
character(len=500) function fruit_util::to_s::to_s_logical_ (logical, intent(in) value) private
Definition at line 76 of file fruit_util.f90.
Referenced by fruit_util::to_s_logical_().
character(len=500) function fruit_util::to_s::to_s_real_ (real, intent(in) value) private
Definition at line 40 of file fruit_util.f90.
Referenced by fruit_util::to_s_real_().
character(len=500) function fruit_util::to_s::to_s_string_ (character(len=*), intent(in) value) private
Definition at line 85 of file fruit_util.f90.
Referenced by fruit_util::to_s_string_().
The documentation for this interface was generated from the following file:
TESTS/fruit/fruit_util.f90