MODEL/help/rdtpmd.h File Reference
rdtpmd.h File Reference
Functions
integer icount (MAX_CAT)
integer npix integer ipixnum (MAX_ROW, MAX_COL)
integer npix integer ixpix (MAX_PIX)
integer npix integer iypix (MAX_PIX) integer icatch(MAX_PIX)
integer npix integer iprn (MAX_FIL) integer ioptlr
integer npix integer iopslp real q0 (MAX_CAT)
integer npix integer iopslp real ff (MAX_CAT)
integer npix integer iopslp real dd (MAX_CAT) real *8 area(MAX_CAT)
integer npix integer iopslp real dtil (MAX_CAT)
integer npix integer iopslp real atanb (MAX_PIX) real *8 xlength(MAX_CAT)
integer npix integer iopslp real basink (MAX_CAT) real *8 zbar1(MAX_CAT)
integer npix integer iopslp real xlamda (MAX_CAT) integer kk
integer npix integer iopslp
real jj real lng_mer integer iwel (MAX_PIX) real *8 atb(MAX_PIX)
integer npix integer iopslp
real jj real lng_mer integer ti (MAX_PIX)
integer npix integer iopslp
real jj real lng_mer integer
hbar0 real * zbar0 (MAX_CAT)
integer npix integer iopslp
real jj real lng_mer integer
hbar0 real sumatb (MAX_CAT)
integer npix integer iopslp
real jj real lng_mer integer
hbar0 real sumlti (MAX_CAT) real *8 qb0(MAX_CAT)
integer npix integer iopslp
real jj real lng_mer integer
hbar0 real lte (MAX_CAT) real *8 rlatitude
Variables
integer iopbf
integer iopwt0
integer ncatch
integer nrow
integer ncol
integer npix integer iopslp real * pixsiz
integer npix integer iopslp
real jj real * lat_deg
integer npix integer iopslp
real jj real lat_min
integer npix integer iopslp
real jj real lng_deg
integer npix integer iopslp
real jj real lng_min
integer npix integer iopslp
real jj real lng_mer integer
hbar0 real rlongitude
Function Documentation
integer npix integer iopslp real atanb (MAX_PIX)
integer npix integer iopslp real basink (MAX_CAT)
integer npix integer iopslp real dd (MAX_CAT)
integer npix integer iopslp real dtil (MAX_CAT)
Referenced by module_topmodel::upzbar().
integer npix integer iopslp real ff (MAX_CAT)
integer icount (MAX_CAT)
integer npix integer ipixnum (MAX_ROW , MAX_COL)
integer npix integer iprn (MAX_FIL)
integer npix integer iopslp real jj real lng_mer integer iwel (MAX_PIX)
integer npix integer ixpix (MAX_PIX)
Referenced by module_io::rdatb().
integer npix integer iypix (MAX_PIX)
Referenced by module_io::rdatb().
integer npix integer iopslp real jj real lng_mer integer hbar0 real lte (MAX_CAT)
Referenced by module_io::rdtpmd().
integer npix integer iopslp real q0 (MAX_CAT)
integer npix integer iopslp real jj real lng_mer integer hbar0 real sumatb (MAX_CAT)
Referenced by module_io::rdtpmd().
integer npix integer iopslp real jj real lng_mer integer hbar0 real sumlti (MAX_CAT)
Referenced by module_io::rdtpmd().
integer npix integer iopslp real jj real lng_mer integer ti (MAX_PIX)
integer npix integer iopslp real xlamda (MAX_CAT)
integer npix integer iopslp real jj real lng_mer integer hbar0 real* zbar0 (MAX_CAT)
Referenced by module_io::rdtpmd().
Variable Documentation
integer iopbf
Definition at line 1 of file rdtpmd.h.
Referenced by module_topmodel::upzbar().
integer iopwt0
Definition at line 1 of file rdtpmd.h.
integer npix integer iopslp real jj real* lat_deg
Definition at line 12 of file rdtpmd.h.
integer npix integer iopslp real jj real lat_min
Definition at line 12 of file rdtpmd.h.
integer npix integer iopslp real jj real lng_deg
Definition at line 12 of file rdtpmd.h.
integer npix integer iopslp real jj real lng_min
Definition at line 12 of file rdtpmd.h.
integer ncatch
Definition at line 1 of file rdtpmd.h.
integer ncol
Definition at line 1 of file rdtpmd.h.
integer nrow
Definition at line 1 of file rdtpmd.h.
integer npix integer iopslp real* pixsiz
Definition at line 6 of file rdtpmd.h.
integer npix integer iopslp real jj real lng_mer integer hbar0 real rlongitude
Definition at line 18 of file rdtpmd.h.