      integer ipix,i,inc_frozen,i_2l,i_und,i_moss,ivgtyp
      integer iopthermc,iopgveg,iopthermc_v,iopsmini,ikopt
      integer irestype,ioppet,iopveg,ievcon,ievcon_us,ievcon_moss
      integer ifcoarse,irntyp,idifind
      integer istmst,intstm,istmst_moss,intstm_moss,intstp,istorm
      integer initer,iffroz,iffroz_us,maxnri,newstorm

      real*8 rzsm_test,tzsm_test,rzsm_u_test,tzsm_u_test,thetas_add

      real*8 mul_fac
      real*8 dt,canclos,extinct,PackWater,SurfWater,Swq
      real*8 VaporMassFlux,TPack,TSurf,r_MeltEnergy,Outflow
      real*8 xleact_snow,hact_snow,rn_snow,PackWater_us,SurfWater_us
      real*8 Swq_us,VaporMassFlux_us,TPack_us,TSurf_us
      real*8 r_MeltEnergy_us,Outflow_us,xleact_snow_us,hact_snow_us
      real*8 rn_snow_us,dens,dens_us,albd_us,alb_moss,alb_snow,albd
      real*8 rsd,rld,tcel,vppa,psychr,xlhv,tkel,zww,za,uzw,press,pptms
      real*8 appa,vpsat,tcel_ic,vppa_ic,psychr_ic,xlhv_ic,tkel_ic
      real*8 vpsat_ic,precip_o,precip_u,tkmid,tkact,tkmid_us
      real*8 tkact_us,tskinact_moss,tkact_moss,tkmid_moss
      real*8 tkmidpet,tkmidpet_us,tkmidpet_moss,tsoilold
      real*8 Tdeepstep,dshact,rnetpn,gbspen,epetd,evtact
      real*8 bsdew,gact,rnact,xleact,hact,epetd_us,dshact_moss
      real*8 xle_act_moss,rnetd,xled,hd,gd,dshd,tkd,tkmidd
      real*8 rnetw,xlew,hw,gw,dshw,tkw,tkmidw,rnact_us,xleact_us
      real*8 hact_us,gact_us,dshact_us,rnetw_us,xlew_us,hw_us
      real*8 gw_us,dshw_us,tkw_us,tkmidw_us,evtact_us,rnetd_us
      real*8 xled_us,hd_us,gd_us,dshd_us,tkd_us,tkmidd_us,bsdew_moss
      real*8 evtact_moss,rnet_pot_moss,xle_p_moss,h_p_moss,g_p_moss
      real*8 tk_p_moss,tkmid_p_moss,tskin_p_moss,eact_moss
      real*8 rnact_moss,xleact_moss,hact_moss,gact_moss
      real*8 thetar,thetas,psic,bcbeta,quartz
      real*8 rocpsoil,tcbeta,tcbeta_us,bulk_dens,a_ice,b_ice
      real*8 xk0,bcgamm,srespar1,srespar2,srespar3
      real*8 zdeep,zmid,zrzmax,r_moss_depth,thetas_moss,srespar1_moss
      real*8 srespar2_moss,srespar3_moss,eps,emiss_moss,zpd_moss
      real*8 rib_moss,z0m_moss,z0h_moss,epet_moss,xlai,xlai_us
      real*8 emiss,zpd,zpd_us,z0m,z0h,f1par,f3vpd,f4temp,f1par_us
      real*8 f3vpd_us,f4temp_us,rescan,tc,tw,tc_us,tw_us,rescan_us
      real*8 rtact,rtdens,psicri,respla,f1,f2,f3,emiss_us
      real*8 row,cph2o,roa,cp,roi,toleb,roa_ic,ravd
      real*8 rahd,ravd_us,rahd_us,rav_moss,rah_moss,rib
      real*8 RaSnow,rzsm,tzsm,rzsm1,tzsm1,rzsm_u,tzsm_u
      real*8 rzsm1_u,tzsm1_u,rzsm_f,tzsm_f,rzsm1_f,tzsm1_f
      real*8 r_mossm,r_mossm1,r_mossm_f,r_mossm1_f,r_mossm_u,r_mossm1_u
      real*8 zrz,ztz,r_mossmold,smold,rzsmold,tzsmold
      real*8 rzdthetaudtemp,rzdthetaidt,tzdthetaidt,zw,zbar
      real*8 zmoss,capflx,difrz,diftz,grz,gtz,pnet,cuminf,sorp
      real*8 cc,deltrz,xinact,satxr,xinfxr,runtot,sesq
      real*8 corr,dc,fw,dc_us,fw_us,wcip1,par,dewrun
      real*8 dsrz,rzrhs,ff,atanb,xlamda,fwcat,fwreg,dstz,tzrhs
      real*8 pr1rzs,pr1tzs
      real*8 persxr,perixr,persac,peruac,perusc
      real*8 zero,one,two,three,four,five,six,tolinf
      real*8 f_moss,f_und,ds_p_moss
      real*8 rain,snow,rs_over,rs_under,smtmp,thermc1,thermc2
      real*8 heatcap1,heatcap2,heatcapold,thermc,heatcap
      real*8 heatcap_us,thermc_us,thermc_moss,heatcap_moss
      real*8 tkactd,tkmidactd,tkactd_us,tkmidactd_us,tskinactd_moss
      real*8 tkactd_moss,tkmidactd_moss,rzsmst,xinfcp,rsoil,ebscap
      real*8 tsnow,dum,gactd,smcond,smcond_us,vegcap,vegcap_us
      real*8 srzrel,psisoi,xksrz,ressoi,xkrz,stzrel,xkstz
      real*8 xktz,r_sdn,r_ldn
!      real*8 dewrz
      real*8 xleactd,rnactd,hactd,dshactd
      real*8 r_lup,tdiff,rnactd_us,xleactd_us,hactd_us,gactd_us
      real*8 dshactd_us,trlup,xleactd_moss,hactd_moss,gactd_moss
      real*8 dshactd_moss,rnactd_moss,p1,p2,p3,r_dens
      real*8 evrz_moss
      real*8 a_ice_moss,b_ice_moss,bulk_dens_moss,zw0
      data zero,one,two,three,four,five,six/0.d0,1.d0,2.d0,&
             3.d0,4.d0,5.d0,6.d0/
