      integer ievcon_us,i_und,i_moss,ipix,iffroz_us,iopthermc,i
      integer ifcoarse,inc_frozen,iopgveg,iopthermc_v
      integer initer,i_2l,ievcon_moss,maxnri

      real*8 ccc,rain,snow,canclos,rnact_us,xleact_us,hact_us
      real*8 gact_us,dshact_us,tkact_us,tkmid_us,rnactd_us,rnetw_us
      real*8 xleactd_us,xlew_us,hactd_us,hw_us,gactd_us,gw_us
      real*8 dshactd_us,dshw_us,tkactd_us,tkw_us,tkmidactd_us
      real*8 tkmidw_us,dc_us,fw_us,trlup,xlhv_ic,row,evtact_us
      real*8 tkmid,zmid,zrzmax,smtmp,rzsm,tzsm,smold,rzsmold
      real*8 tzsmold,thermc1,thermc2,thetar,thetas,psic,bcbeta
      real*8 quartz,heatcap1,heatcap2,heatcapold,rocpsoil
      real*8 cph2o,roa,cp,roi,thermc,heatcap,rzdthetaudtemp
      real*8 thermc_us,tcbeta_us,xlai,f3,albd_us,emiss_us,ravd_us
      real*8 rahd_us,rescan_us,tcel_ic,vppa_ic,roa_ic,psychr_ic
      real*8 zdeep,Tdeepstep,r_sdn,r_ldn,toleb,dt
      real*8 rld,rnetd_us,xled_us,hd_us,gd_us,dshd_us,tkd_us,tkmidd_us
      real*8 xleactd_moss,bsdew_moss,evtact_moss,thermc_moss,heatcap_moss
      real*8 r_mossm,tskinactd_moss,tskinact_moss,tkactd_moss
      real*8 tkact_moss,tkmidactd_moss,tkmid_moss,hactd_moss
      real*8 gactd_moss,dshactd_moss,rav_moss,rah_moss,r_moss_depth
      real*8 alb_moss,rnactd_moss,emiss_moss,eact_moss,rnet_pot_moss
      real*8 xle_p_moss,h_p_moss,g_p_moss,ds_p_moss,tk_p_moss
      real*8 tkmid_p_moss,tskin_p_moss,zmoss,thetas_moss
      real*8 rnact_moss,xleact_moss,hact_moss,gact_moss,dshact_moss
      real*8 Swq_us,precip_u,PackWater_us,SurfWater_us,VaporMassFlux_us
      real*8 TPack_us,TSurf_us,r_MeltEnergy_us,Outflow_us,xleact_snow_us
      real*8 hact_snow_us,rn_snow_us,dens_us,alb_snow,za,zpd_us
      real*8 z0h_us,RaSnow,appa,vpsat_ic,uzw,gact,r_lup
      real*8 xlai_us,heatcap_us,tkel_ic,eps
      real*8 zero,one,two,three,four,five,six,albsnow,tsnow
      real*8 told0,told1,told2,hold0,hold1,hold2,tcold0,tcold1,tcold2,dum
      data zero,one,two,three,four,five,six/0.d0,1.d0,2.d0,&
             3.d0,4.d0,5.d0,6.d0/
