      integer ii,j,int,landc,ipix,s_lc,s_px,nodmax

      integer s_mixmax(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1))
      integer s_numnod(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1))

      integer mixmax(1+LAK_FLG*(MAX_PIX-1))
      integer numnod(1+LAK_FLG*(MAX_PIX-1))

      real*8 s_preca_a(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1))
      real*8 s_tp_in(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1))
      real*8 s_hice_in(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1))
      real*8 s_hsnw_in(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1))
      real*8 s_temp_a(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1),1+LAK_FLG*(MAX_NOD-1))
      real*8 s_tempi_a(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1))
      real*8 s_hice_a(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1))
      real*8 s_hsnow_a(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1))
      real*8 s_xlat_a(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1))
      real*8 s_xlong_a(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1))
      real*8 s_eta_a(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1))
      real*8 s_surface(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1),1+LAK_FLG*(MAX_NOD-1))
      real*8 s_fraci_a(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1))
      real*8 s_precacc(MAX_ATB,1+LAK_FLG*(MAX_VST-1),1+LAK_FLG*(MAX_PP1-1))

      real*8 preca_a(1+LAK_FLG*(MAX_PIX-1))
      real*8 tp_in(1+LAK_FLG*(MAX_PIX-1))
      real*8 hice_in(1+LAK_FLG*(MAX_PIX-1))
      real*8 hsnw_in(1+LAK_FLG*(MAX_PIX-1))
      real*8 temp_a(1+LAK_FLG*(MAX_PIX-1),1+LAK_FLG*(MAX_NOD-1))
      real*8 tempi_a(1+LAK_FLG*(MAX_PIX-1))
      real*8 hice_a(1+LAK_FLG*(MAX_PIX-1))
      real*8 hsnow_a(1+LAK_FLG*(MAX_PIX-1))
      real*8 xlat_a(1+LAK_FLG*(MAX_PIX-1))
      real*8 xlong_a(1+LAK_FLG*(MAX_PIX-1))
      real*8 eta_a(1+LAK_FLG*(MAX_PIX-1))
      real*8 surface(1+LAK_FLG*(MAX_PIX-1),1+LAK_FLG*(MAX_NOD-1))
      real*8 fraci_a(1+LAK_FLG*(MAX_PIX-1))
      real*8 precacc(1+LAK_FLG*(MAX_PIX-1))
